kustomize/rook-cluster/rook-cluster.yaml
Bump current ceph version to 18.2.1
=> bump ceph version 18.2.1

ansible/roles/host_setup/vars/debian.yaml
This change adds a debian variables file so that we can run debian.
=> Add Debian support

.github/workflows/kustomize-ingress.yaml, .github/workflows/kustomize-k8s-dashboard.yaml, .github/workflows/kustomize-libvirt.yaml, .github/workflows/kustomize-mariadb-cluster.yaml, .github/workflows/kustomize-mariadb-operator.yaml, .github/workflows/kustomize-memcached.yaml, .github/workflows/kustomize-openstack.yaml, .github/workflows/kustomize-ovn.yaml, .github/workflows/kustomize-rabbitmq-cluster.yaml, .github/workflows/kustomize-rabbitmq-operator.yaml, .github/workflows/kustomize-rabbitmq-topology-operator.yaml, .github/workflows/kustomize-rook-cluster.yaml, .github/workflows/kustomize-rook-defaults.yaml, .github/workflows/kustomize-rook-operator.yaml, .github/workflows/kustomize-skyline.yaml, .github/workflows/kustomize-topolvm.yaml
This change will ensure all of our kustomize targets build and will only
gate a target when a change is made to that specific location.
=> Add test for kustomize

.github/workflows/helm-cinder.yaml, .github/workflows/helm-glance.yaml, .github/workflows/helm-heat.yaml, .github/workflows/helm-horizon.yaml, .github/workflows/helm-keystone.yaml, .github/workflows/helm-neutron.yaml, .github/workflows/helm-nova.yaml, .github/workflows/helm-octavia.yaml, .github/workflows/helm-placement.yaml
This change updates the helm workflows to ensure that the helm check is run if any change is made to a related kustomize file.
=> Add Kustomize files to helm workflows

.gitignore, ansible/playbooks/ansible.cfg
Reverts rackerlabs/genestack#54
=> Revert "adjust ansible output and where collections are installed"

.github/workflows/kustomize-vault-secrets-operator.yaml, kustomize/vault-secrets-operator/base/kustomization.yaml, kustomize/vault-secrets-operator/base/namespace.yaml, kustomize/vault-secrets-operator/base/values.yaml
Add kustomization for installing vault-secrets-operator.
=> Add vault-secrets-operator installation chart

kustomize/rook-cluster/rook-cluster.yaml
Bump 18.2.1 to 18.2.2 latest stable ceph release
=> Update to latest stable ceph release

docs/infrastructure-mariadb.md, docs/k8s-labels.md, kustomize/mariadb-cluster/base/mariadb-maxscale.yaml, kustomize/mariadb-operator/kustomization.yaml
Add some logging, beatify some docs, doing things.
=> General cleanup things

docs/storage-swift-object-store.md
=> OSPC-324-storage-swift-object-store-intial

kustomize/mariadb-cluster/base/mariadb-galera.yaml
Config change to turn off retry on autocommit. This is causing database inconsistency.
=> Deadlock fix

docs/storage-ceph-rook-external.md
We need to pull from submodule pin version and not master
=> Version lock ceph images to upstream

bootstrap.sh, scripts/genestack.rc
=> Fix bootstrap

docs/storage-swift-object-store.md
=> DOC-OSPC-324-swift-add-delete-at

mkdocs.yml
Moved under a different section.
=> DOC-OSPC-324-add-swift

docs/openstack-keystone-federation.md, docs/openstack-keystone-readonly.md, etc/keystone/mapping.json, mkdocs.yml
This change will permit readonly access to a given project/domain.
=> feat: add Readonly user documentation

docs/openstack-servers.md, docs/openstack-volumes.md, mkdocs.yml
Updated Servers Page and created Volumes Page
=> DOC: Openstack Volumes

docs/infrastructure-ovn.md, docs/ovn-intro.md, docs/ovn-troubleshooting.md, mkdocs.yml
=> doc: Add some introduction and troubleshooting documentation for OVN

docs/ovn-traffic-flow-intro.md, mkdocs.yml
=> doc: Add OVN traffic flow introduction.

docs/infrastructure-mariadb-ops.md
This is just a basic primer to get the end user started if/when they need to interact with the MaxScale rest API.
=> docs: Add snippet about how to use maxscale api

docs/k8s-kubespray.md
Otherwise `hostname -f` will give you localhost
=> fix: fqdn should come before alias

Containerfiles/NovaEFI-Containerfile
Adding NFS Common package for NFS support
=> Add NFS Common package

docs/infrastructure-gateway-api.md
Add some missing information to the doc.
=> Fix gateway api document

kustomize/skyline/base/configmap-bin.yaml, kustomize/skyline/base/deployment-apiserver.yaml
Updated skyline deployment YAML with the latest skyline image sourced from the repository: https://github.com/rackerlabs/skyline-rxt.
=> Updated skyline deployment yaml with the latest image

kustomize/skyline/base/configmap-bin.yaml, kustomize/skyline/base/deployment-apiserver.yaml
Modified quota ring colors and set Genestack logo to relative in new skyline-console
=> Updated Skyline deployment YAML with the new image featuring modifications to the quota ring and Genestack logo position.

.github/workflows/release-horizon-rxt.yml, .github/workflows/release-keystone-rxt.yml, .github/workflows/release-neutron-oslodb.yaml, .github/workflows/release-nova-oslodb.yaml, .github/workflows/release-nova-uefi.yml
Adds support to build container images for 2024.1
=> Fix: Add entries for 2024.1

ansible/playbooks/deploy-cinder-volumes-reference.yaml
Bump version to match rest of deployment
=> Update deploy-cinder-volumes-reference.yaml to 2024.1

ansible/playbooks/deploy-cinder-volumes-reference.yaml, ansible/playbooks/host-setup.yml, docs/openstack-cinder.md
Adding support for multipath and iscsi
=> Add support for iscsi multipath

ansible-collection-requirements.yml
The kubernetes.core ansible collection needs to updated to 3.2.0 to utilize the enable_helm attribute of the kubernetes.core.kustomize.lookup which was added in 3.1.0
See:
- https://github.com/ansible-collections/kubernetes.core/blob/main/CHANGELOG.rst#v3-1-0
- https://github.com/ansible-collections/kubernetes.core/issues/568
Ansible task example:
- name: Deply mariadb operator
kubernetes.core.k8s:
definition: "{{ lookup('kubernetes.core.kustomize', binary_path='/usr/local/bin/kubectl', dir='/opt/genestack/kustomize/mariadb-operator', enable_helm=True) }}"
namespace: mariadb-system
apply: true
server_side_apply:
field_manager: ansible
force_conflicts: true
state: present
When the play is run with kubernetes .core 3.0.0
```
(genestack) …
```
=> Update kubernetes.core ansible collection to 3.2.0

docs/openstack-pci-passthrough.md
Just a small change to add tip to remind to check that iommu is loaded.
=> Add tip to verify iommu is loaded

kustomize.example/gateway/grafana-routes.yaml, kustomize.example/gateway/internal-gateway-api.yaml
Updating gateway that has letsencrypt based https
services.
=> Adds letsencrypt enabled gateway for services

helm-configs.example/nova/nova-helm-overrides.yaml
Adding workarounds config to skip cpu checks
during destination check and startup. This allows
for enabling of these checks to allow live-migration to
work smoothly.
=> Adds cpu mode check workaround

README.md
=> Adds README.md back into the repo

docs/openstack-flavors.md
Docs: https://docs.openstack.org/nova/latest/configuration/extra-specs.html
=> fix: update the flavor docs for new extraspecs

docs/infrastructure-mariadb-ops.md
Document how to properly create target database as required by currently documented dump strategy. Also fix the service name we restore against to be the primary host as `mariadb-cluster` may resolve to a secondary node resulting in unexpected restore issues.
=> docs: cite db creation syntax and fix service name

docs/openstack-clouds.md, docs/openstack-floating-ips.md, docs/openstack-servers.md, docs/prometheus-openstack-metrics-exporter.md
This change updates the clouds.yaml references to ensure proper syntax highlighting and creates references to user generated config as well as provides a reference to use multifactor auth.
=> fix: update the clouds.yaml references

ansible/playbooks/host-setup.yml, ansible/playbooks/templates/genestack-multipath.conf, docs/openstack-cinder.md
Adding in bits to deploy custom multipath bits using ansible.
=> Create ansible bits to deploy custom multipath conf

bootstrap.sh
cp tries to copy a file with an asterisk in the name otherwise
=> fix: need to expand the asterisk here

base-kustomize/ovn/ovn-backup/ovn-backup.config, base-kustomize/ovn/ovn-backup/ovn-backup.sh, base-kustomize/prometheus-pushgateway/kustomization.yaml, base-kustomize/prometheus-pushgateway/values.yaml, base-kustomize/prometheus/alerting_rules.yaml, docs/monitoring-getting-started.md, docs/prometheus-monitoring-overview.md, docs/prometheus-pushgateway.md, mkdocs.yml
=> feat: add Prometheus pushgateway and metric collection for OVN backup

docs/infrastructure-namespace.md
But do not include it in the code block for copy/paste
=> docs: call attention to region param

docs/ovn-monitoring-introduction.md, mkdocs.yml
=> doc: OVN monitoring introduction

base-kustomize/skyline/base/configmap-bin.yaml
update the skyline config to use flavor families.
=> fix: Update configmap-bin.yaml

base-helm-configs/nginx-gateway-fabric/helm-overrides.yaml, docs/infrastructure-gateway-api.md
This updates to 1.4.x so that we can use some additional features like TLS Passthrough.
=> feat: update the gateway api to 1.4.x

docs/openstack-glance-images.md
Also update the opensuse image.
=> docs: rm virtio-scsi in favor of virtio-blk

base-helm-configs/nova/nova-helm-overrides.yaml, docs/openstack-glance-images.md
=> fix: bump num pcie devices and limit disk devs

docs/adding-new-node.md, docs/openstack-pci-passthrough.md, mkdocs.yml
Adding docs to add new node(s) to the cluster.
=> Adds docs to add new node to cluster

docs/adding-new-node.md, docs/openstack-pci-passthrough.md, mkdocs.yml
Update docs for pci passthrough and host aggregate
=> Update docs for pci passthrough and host aggregate

docs/openstack-flavors.md
This change is updating our flavor docs to cover how we create flavors for production environments.
=> feat: Add flavor details to the docs

docs/openstack-object-storage-swift.md
Closing out public facing documentation on OSPC-667
=> Create new documentation for Swift Object Storage

scripts/openstack-run-all.sh
Adding Barbican support into script openstack-run-all.sh
=> Add barbican install to openstack-run-all.sh

mkdocs.yml
Adding Swift Operators guide and Overview to Swift Obj storage to docs.rackspacecloud.com
=> Add swift operations and overview to docs

docs/adding-new-node.md
This is a useful taint operators can make use of.
=> docs: add information about PreferNoSchedule taint

docs/ovn-alert-claim-storm.md, mkdocs.yml
=> doc: OVN claim storm alert

.gitignore
Add Panic's Nova config dir .nova to .gitignore
=> Add Nova editor config to .gitignore

docs/openstack-cloud-design-overview.md
Fix various typos in cloud design docs
=> Fix typos in cloud design docs

docs/openstack-cloud-design-regions.md
docs: Complete Region-level design documentation
=> docs: Complete Region-level design documentation

README.md
Add badging for deliverables that we ship from Genestack.
Issue: https://rackspace.atlassian.net/browse/OSPC-707
=> feat: add publishing badge to the readme

ansible/playbooks/deploy-cinder-netapp-volumes-reference.yaml
These edits apply the playbook correctly.
=> fix: Edit cinder volume netapp playbook: OSPC-802

Containerfiles/etcd-backup/Containerfile, Containerfiles/etcd-backup/backup.py, base-kustomize/backups/etcd/etcd-backup.yaml, docs/etcd-backup.md
Updates etcd backup script and updates the docs
to reflect the changes. This switches to use the newer boto3 and uses swift endpoint to backup etcd backups.
JIRA:OSPC-368
=> Update etcd backup to use swift s3 endpoint

base-helm-configs/nova/nova-helm-overrides.yaml
=> fix: OSPC-729 rename availability zones to az1

mkdocs.yml
This change updates the doc tree for the operations guide to create a better flow of information. The docs now aggregate major topics and give the reader a better sense of the overall project structure.
=> feat: Doc tree update

docs/openstack-quota-managment.md, mkdocs.yml
Adds docs for quota management.
=> Docs: Add quota management

bin/chart-install-meta.yaml, bin/install-chart.sh, bin/yamlparse.py
the install scripts for using the chart would run repetitive with the boilerplate, so this tries to get it in one script
=> feat: chart install script

docs/openstack-cloud-design-az.md, docs/openstack-cloud-design-dr.md, mkdocs.yml
Add design documentation for Availability Zones and update mkdocs.yml structure to add a placeholder for DR information.
=> docs: Add AZ design docs and placeholder for DR

docs/documentation-standards.md, mkdocs.yml
Add a style guide to the documentation.
=> docs: Add Style Guide

docs/infrastructure-ovn-setup.md, docs/storage-ceph-rook-external.md
Some small changes found during a lab deployment.
=> update deployment docs

docs/storage-longhorn.md, docs/storage-overview.md, mkdocs.yml
This change documents how to deploy longhorn for Genestack purposes.
=> feat: document longhorn usage

docs/storage-object-store-s3-cli.md, mkdocs.yml
Closes-Issue: https://rackspace.atlassian.net/browse/OSPC-788
=> feat: add S3 documentation

.original-images.json
=> add neutron image to .original-images.json

.github/workflows/release-octavia-ovn.yml, .github/workflows/smoke-octavia-ovn.yml, Containerfiles/OctaviaOVN-Containerfile
Update the octavia container images to use the new stable images from OpenStack Helm.
=> fix: Add stable container images for octavia

.github/workflows/image-pull-and-tag.yaml, .github/workflows/testing-deploy-openstack.yaml, testing/build.yaml, testing/cleanup.sh, testing/deploy.yaml, testing/doit.sh, testing/env.yaml.example, testing/fix-root.yaml, testing/requirements.txt, testing/single.yaml
Automation to gather images for community edition
=> Community deploy

.github/workflows/release-ceilometer.yaml, .github/workflows/release-cinder-netapp.yml, .github/workflows/release-gnocchi.yaml, .github/workflows/release-heat-rxt.yml, .github/workflows/release-horizon-rxt.yml, .github/workflows/release-neutron-oslodb.yaml, .github/workflows/release-nova-oslodb.yaml, .github/workflows/release-nova-uefi.yml, .github/workflows/release-octavia-ovn.yml
With this change, pushing images into GHCR will automatically create a bot pull request to update our images json file.
=> chore: update nova image

ansible/roles/host_setup/handlers/main.yml
The new queue handler was named wrong, this resolves that.
=> fix: correct typo

base-helm-configs/placement/placement-helm-overrides.yaml
This change will tell placement to use the randomizer which will help a better spread of instances across the environment.
=> feat: tweak placement

base-helm-configs/nova/nova-helm-overrides.yaml
This change will ensure that the instance disk is provisioned before hand.
=> chore: improve instance performance

bin/install-barbican.sh, bin/install-ceilometer.sh, bin/install-cinder.sh, bin/install-fluentbit.sh, bin/install-glance.sh, bin/install-gnocchi.sh, bin/install-grafana.sh, bin/install-heat.sh, bin/install-horizon.sh, bin/install-keystone.sh, bin/install-libvirt.sh, bin/install-magnum.sh, bin/install-mariadb-operator.sh, bin/install-memcached.sh, bin/install-neutron.sh, bin/install-nova.sh, bin/install-octavia.sh, bin/install-placement.sh, bin/install-postgres-operator.sh, bin/install-prometheus.sh, bin/install-template.sh, bin/setup-hosts.sh, bootstrap.sh
Updated install scripts to accept a global override as well as service override and corrected bootstrap to setup the global overrides directory as well as the service overrides directorys
=> Updated install scripts

docs/storage-object-store-s3-cli.md
The position of the conf section was not aligned with the example.
=> fix: doc bug

yaml-editor/requirments.txt, yaml-editor/ye
Created yaml editor to help with creating/updating override files
=> Yaml Editor

base-helm-configs/loki/loki-helm-minio-overrides-example.yaml, base-helm-configs/loki/loki-helm-s3-overrides-example.yaml, base-helm-configs/loki/loki-helm-swift-overrides-example.yaml
Added serviceMonitor for scrapping Loki metrics by prometheus
=> OSPC-1003: Loki metrics are not being scraped by prometheus

ansible/inventory/genestack/group_vars/all/all.yml, ansible/roles/host_setup/tasks/CPU_frequency.yml, ansible/roles/host_setup/tasks/main.yml, docs/k8s-kubespray.md
This commit creates a var to allow the tuned profile to be set. Useful in environments where power consumption might be a consideration.
=> Create var to allow tuned profile to be tuned

bin/install-prometheus.sh, docs/alerting-info.md, docs/k8s-labels.md, docs/prometheus.md, docs/storage-ceph-rook-internal.md
=> Fixed: Doc and script updates

docs/openstack-octavia.md
This change updates the octavia docs so that it is easier to grok what a deployer must do to have a successful installation of octavia.
=> chore: tweak octavia docs

.github/workflows/release-neutron-oslodb.yaml, Containerfiles/Neutron-oslo_db-Containerfile
This change will ensure that our version of Neutron is allowing operators to execute with an additive sync model. Additive sync ensures that we can protect the OVN DB while also ensuring that Neutron is able to automatically resolve issues when they arrive.
=> fix: Rebuilds neutron to ensure sync compatibility

docs/sync-fernet-keys.md
Adding the steps to use pushsecret to sync
secrets between k8s clusters.
=> Update docs on secret syncing

.github/workflows/helm-topolvm.yaml, base-kustomize/topolvm/base/kustomization.yaml, base-kustomize/topolvm/base/namespace.yaml, bin/install-topolvm.sh
install-topolvm.sh was not working properly with previous PR https://github.com/rackerlabs/genestack/pull/810/ to install topolvm via helm. So modified the script and created this PR.
=> OSPC-898: Conversion of topolvm from kustomize to helm

base-helm-configs/prometheus-snmp-exporter/values.yaml, base-kustomize/prometheus-snmp-exporter/base/kustomization.yaml, bin/chart-install-meta.yaml
=> F5 alert snmp v3

docs/infrastructure-rabbitmq.md, docs/monitoring-getting-started.md
Adds docs on using rabbitmq operator provided
monitoring.
=> Add rabbitmq monitoring docs

.github/workflows/helm-prometheus-snmp-exporter.yaml
JIRA:OSPC-624
I probably should've had this in already-merged https://github.com/rackerlabs/genestack/pull/841 but I forgot it there.
=> fix: Add GitHub actions for Prometheus SNMP exporter

docs/build-test-envs.md, scripts/hyperconverged-lab.sh
This change adds an idempotent script that will produce a quick 3 node genestakc lab within an OpenStack cloud. This tool is intended to highlight capabilities of our platform without requiring much in the way of investment of resources or time.
=> feat: Lab script

base-helm-configs/barbican/barbican-helm-overrides.yaml, base-helm-configs/ceilometer/ceilometer-helm-overrides.yaml, base-helm-configs/cinder/cinder-helm-overrides.yaml, base-helm-configs/designate/designate-helm-overrides.yaml, base-helm-configs/glance/glance-helm-overrides.yaml, base-helm-configs/gnocchi/gnocchi-helm-overrides.yaml, base-helm-configs/heat/heat-helm-overrides.yaml, base-helm-configs/keystone/keystone-helm-overrides.yaml, base-helm-configs/magnum/magnum-helm-overrides.yaml, base-helm-configs/neutron/neutron-helm-overrides.yaml, base-helm-configs/nova/nova-helm-overrides.yaml, base-helm-configs/octavia/octavia-helm-overrides.yaml, base-helm-configs/placement/placement-helm-overrides.yaml
Standardize the oslo_messaging_rabbit config's across all supported openstack versions.  filter the yml's through code standardizations.
=> chore: standardize oslo_messaging_rabbit configs

base-kustomize/ovn-backup/base/ovn-backup.yaml, docs/infrastructure-ovn-db-backup.md
=> chore: update OVN backup image version

base-helm-configs/barbican/barbican-helm-overrides.yaml, base-helm-configs/ceilometer/ceilometer-helm-overrides.yaml, base-helm-configs/cinder/cinder-helm-overrides.yaml, base-helm-configs/designate/designate-helm-overrides.yaml, base-helm-configs/glance/glance-helm-overrides.yaml, base-helm-configs/gnocchi/gnocchi-helm-overrides.yaml, base-helm-configs/heat/heat-helm-overrides.yaml, base-helm-configs/horizon/horizon-helm-overrides.yaml, base-helm-configs/keystone/keystone-helm-overrides.yaml, base-helm-configs/magnum/magnum-helm-overrides.yaml, base-helm-configs/neutron/neutron-helm-overrides.yaml, base-helm-configs/nova/nova-helm-overrides.yaml, base-helm-configs/octavia/octavia-helm-overrides.yaml, base-helm-configs/placement/placement-helm-overrides.yaml, base-kustomize/skyline/base/deployment-apiserver.yaml
update entrypoint image to latest-ubuntu_jammy tag for helm and kustomize
=> update entrypoint image to latest-ubuntu_jammy tag for helm values

base-kustomize/grafana/base/grafana-database.yaml, base-kustomize/mariadb-cluster/base/mariadb-replication.yaml
fix for: https://github.com/rackerlabs/genestack/issues/236
=> fix: issue-236 correct deprecated values

bin/create-secrets.sh, docs/etcd-backup.md
Adding etcd-backup-secrets so it gets created automatically and updated the etcd-backup document also.
=> OSPC-1033 Adding etcd-backup-secrets so it gets created automatically

scripts/hyperconverged-lab.sh
Debian does not have git installed by default.  We need to install it ourselves.
=> fix: lab script needs to install git on Debian

scripts/hyperconverged-lab.sh
Addresses issues with the hyperconverged lab script, including a broken URL and disabling SSH warning prompts.
=> Update hyperconverged lab script to fix deployment issues

.original-images.json
Adding masakari and masakari-monitor images to internal repo
=> chore: Update original images

base-helm-configs/glance/glance-helm-overrides.yaml
Removing two policy lines that broke BFV.
=> FIX! (Glance): download policy manual reversion.

base-helm-configs/glance/glance-helm-overrides.yaml
Removing two policy lines that broke BFV.
(cherry picked from commit 274f7d796c4d0e360992e8d4ab4565e01082f2f9)
=> FIX! (Glance): download policy manual reversion. (#960)

mkdocs.yml
Update doc title to be relevant to all Rackspace OpenStack products (not just Flex) and update copyright to 2025
=> fix: Update docs title and copyright

docs/infrastructure-envoy-gateway-api.md, docs/infrastructure-metallb.md, manifests/metallb/metallb-openstack-service-lb.yml
- Fix typos
- Add instructions how to re-IP the pools
- Update cidr example to use a lower range for the gateway api vs upper cidr for the pimrary pool
=> Update metallb documentation

docs/maridb-backuprestore-from-tempauth.md
Created this Document as part of this Jira- OSPC-1141, to restore the mariaDBbackup from the swift tempauth.
This Document is purely based on the Document references and search , which I alreadyd added as part of this document.
This document will be first validated into Staging or Dev, before applying to the Production Environment.
=> Docs: Added document for mariadb backup restore with swift tempauth

.original-images.json
Adding freezer images to genestack repo so that we can use these images to setup freezer.
=> chore: Add freezer images to genestack repo

base-helm-configs/barbican/barbican-helm-overrides.yaml, base-helm-configs/ceilometer/ceilometer-helm-overrides.yaml, base-helm-configs/cinder/cinder-helm-overrides.yaml, base-helm-configs/designate/designate-helm-overrides.yaml, base-helm-configs/glance/glance-helm-overrides.yaml, base-helm-configs/gnocchi/gnocchi-helm-overrides.yaml, base-helm-configs/heat/heat-helm-overrides.yaml, base-helm-configs/keystone/keystone-helm-overrides.yaml, base-helm-configs/libvirt/libvirt-helm-overrides.yaml, base-helm-configs/magnum/magnum-helm-overrides.yaml, base-helm-configs/masakari/masakari-helm-overrides.yaml, base-helm-configs/neutron/neutron-helm-overrides.yaml, base-helm-configs/nova/nova-helm-overrides.yaml, base-helm-configs/octavia/octavia-helm-overrides.yaml, base-helm-configs/placement/placement-helm-overrides.yaml
This will ensure that the lifecycle of the pods has a consistent install and upgrade experience.
=> chore: add lifecycle management for all of the openstack services

bin/create-secrets.sh, bin/install-horizon.sh
The shared secret for horizon is now properly configured and referenced
=> Fixing horizon secret key

docs/sync-fernet-keys.md
We were using push secret which was not deleting old keys so swited back to fernet-sync.
=> Update docs for fernet sync

etc/gateway-api/routes/custom-alertmanager-routes.yaml
replaces: https://github.com/rackerlabs/genestack/pull/1094
=> Fix typo alertmanager route

base-helm-configs/redis-operator/redis-operator-helm-overrides.yaml, bin/install-redis-operator.sh
I have just modified some changes in order work successfully on the DFW-DEV env,
attached the below logs which tested and verified,
[DFW-DEV_DEPLOYMENT_AND_TEST_RESULT_Successful.zip](https://github.com/user-attachments/files/21670280/DFW-DEV_DEPLOYMENT_AND_TEST_RESULT_Successful.zip)
=> OSPC-1403: Modified the yaml and script file to work on DFW-DEV env

base-helm-configs/octavia/octavia-helm-overrides.yaml
(cherry picked from commit ac850c28a6743b1275d0186fd15156e802c52362)
=> fix: Resolve Octavia server QueuePool limit exceeded errors

scripts/hyperconverged-lab.sh
Reverts rackerlabs/genestack#1152
=> Revert "fix: standardize EOC in script"

yaml-editor/ye
Yaml editor has been improved to pull the values.yaml from the helm chart as well as apply the base yaml from genestack and pull in the overrides file from et/genestack in order to give you a full picture of the config. Then save changes to overrides file only the changes.
=> Fix: Updated ye

base-helm-configs/glance/glance-helm-overrides.yaml
(cherry picked from commit 5cdede92eb8f8cca0811bf4af77cc36ed44eb59f)
=> fix: Adjusting glance download_image policy (#1209)
