Containerfiles/NovaEFI-Containerfile, helm-configs/cinder/cinder-helm-overrides.yaml, helm-configs/nova/nova-helm-overrides.yaml, playbooks/deploy-cinder-volumes-reference.yaml, playbooks/templates/sudoers
This change adds some missing config for cinder compatibility and a couple extra tasks needed in the deployment example playbook which wire the cinder rootwrap conf to cinder itself.
The nova container has been further extended to support the cinder workload as well as resolve missing functionality in the nova python enviroment.
=> Resolve cinder iscsi incompatibilities

Containerfiles/NovaEFI-Containerfile
This will resolve the libosdetect issues in nova. While gi isn't a critical issue, having it will ensure we're running a functionally complete environment.
=> add pygobject

helm-configs/neutron/neutron-helm-overrides.yaml
This change updates our neutron config to remove `dns_domain_ports`. While this is a valid plugin the capability won't be functional until we're ready to deploy designate.
Docs: https://docs.openstack.org/designate/latest/user/neutron-integration.html
=> Remove `dns_domain_ports`

.github/workflows/release-horizon-rxt.yml, Containerfiles/HorizonRXT-Containerfile, helm-configs/horizon/horizon-helm-overrides.yaml
This change adds horizon panels to the system. By default the stock horizon image does not contain panels an operator may want to leverage. To ensure we're able to offer a better horizon experience we're creating a new image which has some additional panels.
A change has been made to include the new panels in horizon's configuration.
=> Create the horizon rxt image

playbooks/deploy-cinder-volumes-reference.yaml
This change updates the example deployment playbook for the cinder reference driver.
=> FIX: Add the missing tgtd include for cinder

helm-configs/osie/osie-helm-overrides.yaml
This change allows us to deploy OSIE within a Genestack environment.
=> Feat: add osie example deployment

bootstrap.sh, openstack-enterprise/inventory-example.yaml, openstack-flex/inventory-example.yaml, scripts/convert_osa_inventory.py
- Rename nova_compute_nodes to openstack_compute_nodes
- Fix k8s-cluster group name for OSA to k8s converter
=> Update openstack-enterprise inventory

ansible/inventory/openstack-enterprise/group_vars/k8s_cluster/k8s-cluster.yml, ansible/inventory/openstack-flex/group_vars/k8s_cluster/k8s-cluster.yml
This change updates flex and ent to use the latest stable k8s release from kubespray. The change has been lab and hardware tested and shown to work well.
``` shell
ubuntu@openstack-flex-launcher:/opt/genestack/submodules/openstack-helm$ kubectl version
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.6
```
Openstack endpoint confirmation
``` shell
ubuntu@openstack-flex-launcher:/opt/genestack/submodules/openstack-helm$ kubectl --namespace openstack exec -ti openstack-admin-client -- openstack endpoint list
+----------------------------------+-----------+--------------+----------------+---------+-----------+---------------------------------------------------------------------+
| ID                               | Region    | Service Name …
```
=> Upgrade to the latest stable k8s

.ansible-lint, .github/workflows/pre-commit.yaml, .github/workflows/release-keystone-rxt.yml, .github/workflows/release-nova-uefi.yml, .github/workflows/release-octavia-ovn.yml, .github/workflows/smoke-horizon-rxt.yml, .github/workflows/smoke-keystone-rxt.yml, .github/workflows/smoke-nova-uefi.yml, .github/workflows/smoke-octavia-ovn.yml, .pre-commit-config.yaml, Containerfiles/HorizonRXT-Containerfile, Containerfiles/KeystoneRXT-Containerfile, Containerfiles/NovaEFI-Containerfile, Containerfiles/OctaviaOVN-Containerfile, ansible/inventory/openstack-enterprise/group_vars/k8s_cluster/addons.yml, requirements.yml
This change updates the builds for the containers to use a multistage build where
applicable. All containers will now also cleanup the pycache files when detected,
ensuring that we're building efficient images. With this change we'll now publish
container images with an epoc so that we can use point in time releases when needed.
This change adds pre-commit hooks to our setup so that we can begin running some
static analysis against our code base.
> To ensure that our tests run we've made a change to the `addons.yml` file to
correct a syntax error.
Ansible-lint config has been added to ignore most of the infractions at this point,
we'll need to address those rule violations as we develop the tool-chain.
=> Add test and tags to builds

.github/workflows/helm-cinder.yaml, .github/workflows/helm-glance.yaml, .github/workflows/helm-heat.yaml, .github/workflows/helm-horizon.yaml, .github/workflows/helm-keystone.yaml, .github/workflows/helm-neutron.yaml, .github/workflows/helm-nova.yaml, .github/workflows/helm-octavia.yaml, .github/workflows/helm-placement.yaml
This change will ensure that out helm charts build when changes are made to our helm overrides.
=> Add helm template actions

helm-configs/octavia/octavia-helm-overrides.yaml
This change adds some additional config to handle octavia's use of the public URL when creating loadbalancer. While most of the calls are done over the internalURL it seems octavia defaults to the publicURL in some cases. This update ensures that we have a functional octavia environment in all cases.
=> Add additional config to ensure ovn+octavia is working

kustomize/ovn/kustomization.yaml, kustomize/ovn/ovn-backup.yaml
Add backups for OVN NB and SB.
Putting this on a persistent volume seems to match what happens with MariaDB from the operator install, so I tried to follow the established convention for now.
=> Add manifests for OVN NB and SB backup.

ansible/playbooks/infra-deploy.yaml
During the infra-deploy playbook, ansible connects to the bastion or launcher node. It's best that this be done with the user's default ssh configuration in lieu of the generated one, otherwise connections to the bastion could fail.
Use ansible.builtin.ping to check liveness which is more thorough of a test. It will use the default ssh config, whereas wait_for ill only attempt a tcp connection, which may fail if a user has a default proxy configured as required in their environment.
=> Use default ssh config when connecting to bastion

.github/workflows/kustomize-argocd.yaml, kustomize/argocd/base/kustomization.yaml, kustomize/argocd/base/namespace.yaml, kustomize/argocd/base/values.yaml, kustomize/ingress/internal/helm/ingress-helm-overrides.yaml
Uses kustomize to deploy argoCD helm chart. 
It expects `argocd-tls-public` Kubernetes secret containing FQDN ssl cert/key. The method of deploying the secret in argocd namespace will vary depending on tool we select(sealed-secret/vault).
=> Add ArgoCD installation chart

kustomize/mariadb-operator/kustomization.yaml
The documentation currently has you ensure your servers have an FQDN, which might lead some people to to give their cluster a name besides the default cluster.local. If you don't put your actual cluster name here, you can't get the MariaDB stuff deployed, so I put in 'cluster.local' to suggest that it should get edited.
=> Put clusterName in kustomize.yaml for the mariadb-operator.

ansible/playbooks/deploy-cinder-volumes-reference.yaml
When using the variable override for the first time to define a different interface for my_ip in cinder.conf, we found the default value getting used instead. The path including ansible_facts is invalid, so remove it.
=> Fix path for iface to not include ansible_facts

scripts/import-external-cluster.sh
Including script to allow import of external ceph cluster for storage classes
=> Include external ceph import script

helm-configs/neutron/neutron-helm-overrides.yaml
Upstream disabled DVR as they found it unstable. I think @busterswt said we want to re-enable this.
Marking as draft, making PR for comments/review. Feel free to close this PR if we don't want to re-enable this.
Upstream disabling:
https://github.com/openstack/openstack-helm/commit/6ae4b98eec6bd5ccd564b24a4b2f0f1f54822df5
=> Upstream disabled DVR with OVN. This commit re-enables it.

.github/workflows/mkdocs.yaml, .gitignore, doc-requirements.txt, mkdocs.yml
Build the existing markdown pages in the docs folder using mkdocs and deploy them to GitHub Pages.
=> feat: build GitHub Pages using mkdocs

ansible/playbooks/infra-deploy.yaml
Extends setup of the launcher instance to simplify initial lab creation.
=> Update infra_deploy to improve lab env creation

ansible/playbooks/infra-deploy.yaml
The linter told me to use `command` in lieu of shell which breaks functionality due to additional commands being treated as extra arguments to the first command. Revert to using shell where needed so the right thing is done.
=> Fix bb5bb3a exec fail using shell in lieu of command

.github/workflows/kustomize-prometheus-rabbitmq-exporter.yaml, kustomize/prometheus-rabbitmq-exporter/kustomization.yaml, kustomize/prometheus-rabbitmq-exporter/values.yaml
Adds rabbitmq-exporter to expose rabbitmq metrics.
JIRA: OSPC-250
=> Adds rabbitmq-exporter for prometheus

docs/index.md
Two docs link were broken due to capital letter begning of the file. This simply change the docs link to point to the right files.
=> Fixes broken docs links

.github/workflows/kustomize-vault.yaml, docs/vault.md, kustomize/vault/base/kustomization.yaml, kustomize/vault/base/namespace.yaml, kustomize/vault/base/ssl/kustomization.yaml, kustomize/vault/base/ssl/vault-ca-issuer.yaml, kustomize/vault/base/ssl/vault-cert.yaml, kustomize/vault/base/ssl/vault-selfsigned-ca.yaml, kustomize/vault/base/ssl/vault-selfsigned-issuer.yaml, kustomize/vault/base/values.yaml
Uses kustomize to deploy vault helm chart.
- Prior installation:
- It requires some storage available in the cluster. As user will install vault prior deploying CEPH, the cluster will not be having any storage configured. Hence, we need to consider local storage from the Kubernetes nodes. We can go with Rancher local path provisioner for the same[1].
- It expects vault-tls-public Kubernetes secret containing FQDN ssl cert/key. We can encrypt "vault-tls-public" using sealed-secret and push to git to consume it using argocd.
[1]
https://github.com/rancher/local-path-provisioner
=> Feat(OSPC-163): Introduce vault

.github/workflows/helm-prometheus-openstack-metrics-exporter.yaml, .gitmodules, docs/openstack-metrics-exporter.md, helm-configs/monitoring/openstack-metrics-exporter/clouds-yaml, helm-configs/monitoring/openstack-metrics-exporter/openstack-metrics-exporter-helm-overrides.yaml
Adding prometheus openstack metrics exporter
=> Monitoring adding openstack metrics exporter

.github/workflows/kustomize-prometheus-mysql-exporter.yaml, docs/index.md, docs/prometheus-mysql-exporter.md, kustomize/prometheus-mysql-exporter/kustomization.yaml, kustomize/prometheus-mysql-exporter/monitoring_user_create.yaml, kustomize/prometheus-mysql-exporter/monitoring_user_grant.yaml, kustomize/prometheus-mysql-exporter/values.yaml, kustomize/prometheus/alerting_rules.yaml
Adding mysql exporter to expose mysql and galera
metrics.
JIRA: OSPC-268
=> Adds mysql prometheus exporter

docs/vault-secrets-operator.md, docs/vault.md
This commit introduces comprehensive documentation for integrating the HashiCorp Vault Secrets Operator into the Genestack installation process.
=> Documentation for HashiCorp Vault Secrets Operator 

kustomize/topolvm/general/kustomization.yaml
This commit disables the installation of cert-manager during the Kubernetes cluster installation. Given that we deploy cert-manager alongside the cluster(kubespray), we can utilize the existing instance for Topolvm integration. 
Additionally, the storage class name has been updated to ensure proper reference during the Vault installation process.
=> Disable Cert-Manager Installation and Update Storage Class Name

kustomize/mariadb-operator/kustomization.yaml
The API group has been renamed in the latest version of mariadb-operator(0.26.0) which breaks the deployment of mariadb cluster installation. https://github.com/mariadb-operator/mariadb-operator/pull/418
=> Specify mariadb-operator chart version to deploy

kustomize/rook-cluster/rook-cluster.yaml, kustomize/rook-operator/common.yaml, kustomize/rook-operator/crds.yaml, kustomize/rook-operator/operator.yaml
Ran into issues with ceph looking for new service account 'rook-ceph-default', bump to current version of ceph and fixup issues preventing cluster creation.
=> Bump Ceph to current version and get working

docs/Deploy-Openstack.md
This showed up with the default 'password' value from the Genestack helm overrides in helm-configs/
JIRA:OSPC-287
=> Fix metadata_shared_secret for Nova and Neutron.

docs/deploy-required-infrastructure.md, helm-configs/gnocchi/gnocchi-helm-overrides.yaml, helm-configs/postgresql/postgresql-helm-overrides.yaml, kustomize/gnocchi/base/configmap-bin.yaml, kustomize/gnocchi/base/gnocchi-temp-keyring.yaml, kustomize/gnocchi/base/kustomization.yaml
This PR introduces helm configs for Gnocchi (OpenStack Metrics API) and its dependency, PostgreSQL. Gnocchi is a dependency of Ceilometer, which we will be adding to Genestack soon.
Note that PostgreSQL is being used as the indexer storage back-end in favor of our existing MariaDB operator implementation for several reasons.
1. Gnocchi [cites PostgreSQL as the preferred driver](https://gnocchi.osci.io/intro.html#indexer-driver) (though they don't state _why_ exactly).
2. I could not get the MySQL driver working with the helm chart, despite several attempts. It seems like it may be possible, but instructions are unclear, and there may be a bit of overhaul with the chart required to get it to work as expected. MySQL is supported by Gnocchi though, so it's within the realm of possibility. …
=> Introduce Gnocchi helm chart to Genestack

docs/infrastructure-overview.md, docs/prometheus-mysql-exporter.md, docs/prometheus-openstack-metrics-exporter.md, docs/prometheus-rabbitmq-exporter.md
Doc updates that tune up some of our docs to make things look more uniform.
=> fix: simple doc updates

.gitmodules, kustomize/cinder/base/cinder-mariadb-database.yaml, kustomize/glance/base/glance-mariadb-database.yaml, kustomize/heat/base/heat-mariadb-database.yaml, kustomize/horizon/base/horizon-mariadb-database.yaml, kustomize/keystone/base/keystone-mariadb-database.yaml, kustomize/mariadb-cluster/base/mariadb-backup.yaml, kustomize/mariadb-cluster/base/mariadb-galera.yaml, kustomize/mariadb-operator/kustomization.yaml, kustomize/neutron/base/neutron-mariadb-database.yaml, kustomize/nova/base/nova-mariadb-database.yaml, kustomize/octavia/base/octavia-mariadb-database.yaml, kustomize/placement/base/placement-mariadb-database.yaml, kustomize/prometheus-mysql-exporter/monitoring_user_create.yaml, kustomize/prometheus-mysql-exporter/monitoring_user_grant.yaml, kustomize/skyline/base/skyline-mariadb-database.yaml
This change is updating the mariadb-galera manifest to use the latest images
and system config. This is being done to help resolve some of the deadlock
issues being experienced when the cluster is under load.
This change also brings in a LOT of fixes into the operator, which should
help make our platform run better, generally.
All of the CRD references have been updated to use the stable release of the
operator, version 0.26.0.
=> MariaDB-Operator updates

docs/k8s-labels.md, docs/vault.md, kustomize/vault/base/kustomization.yaml, kustomize/vault/base/local_storage/kustomization.yaml, kustomize/vault/base/local_storage/local_sc.yaml, kustomize/vault/base/local_storage/vault-dwpp.yaml, kustomize/vault/base/local_storage/vault-fezz.yaml, kustomize/vault/base/local_storage/vault-hprr.yaml, kustomize/vault/base/local_storage/vault-jyff.yaml, kustomize/vault/base/local_storage/vault-ktpw.yaml, kustomize/vault/base/local_storage/vault-uqhy.yaml, kustomize/vault/base/values.yaml
- Instead of relying on third party tool to consume local storage for the Vault, we will make use of native approach of Kubernetes.
=> Implement use of local storage from the nodes for the vault

docs/examples/alertmanager-encore.md, docs/examples/alertmanager-slack.md
Parking intial slack and encore configuration examples for alertmanager
=> Adding initial examples for alertmananger

helm-configs/loki/loki-helm-minio-overrides-example.yaml, helm-configs/loki/loki-helm-s3-overrides-example.yaml, helm-configs/loki/loki-helm-swift-overrides-example.yaml
If one of the loki-write pods moves due to a different node the hash ring can become unhealthy. This will cause logs not to be sent to the backend.  This will further lead to the other write pods to start filling up the volumes that they use and eventually cause dropped logs.
Example error
```
ubuntu@overseer01:~$ k -n grafana logs daemonset.apps/loki-logs --tail 2 -f
Found 37 pods, using pod/loki-logs-m9xvs
ts=2024-03-15T14:42:17.533917001Z caller=client.go:419 level=warn component=logs logs_config=grafana/loki component=client host=loki-gateway.grafana.svc.cluster.local msg="error sending batch, will retry" status=500 tenant= error="server returned HTTP status 500 Internal Server Error (500): at least 2 live replicas required, could only find 1 - unhealthy instances: …
```
=> Update examples with setting to forget unhealthy ingestors

kustomize/ingress/external/helm/ingress-helm-overrides.yaml, kustomize/ingress/grafana/helm/ingress-helm-overrides.yaml, kustomize/ingress/internal/helm/ingress-helm-overrides.yaml, kustomize/mariadb-cluster/base/mariadb-galera.yaml, kustomize/mariadb-cluster/base/mariadb-maxscale.yaml, kustomize/mariadb-operator/kustomization.yaml, kustomize/memcached/base/kustomization.yaml, kustomize/prometheus-mysql-exporter/values.yaml, kustomize/prometheus-postgres-exporter/values.yaml, kustomize/prometheus-rabbitmq-exporter/values.yaml, kustomize/prometheus/values.yaml, kustomize/rabbitmq-cluster/base/rabbitmq-cluster.yaml, kustomize/sealed-secrets/base/values.yaml, kustomize/vault-secrets-operator/base/values.yaml
This change ensures our workloads are scheduled to nodes we're expecting. At present, the assumption is that workloads without specific affinity rules would land on "workers" however, that was wrong. This change ensure that workloads such as memcached, mariadb, and rabbitmq are always scheduled to our appropriate workers.
=> fix: Add Affinity where it's needed

docs/vault-secrets-operator.md
- Fix typos and the command used to install vault-secrets-operator
=> Fix typos and the command used to install vault-secrets-operator

.github/workflows/kustomize-gateway-api.yaml, kustomize/gateway/alertmanager-routes.yaml, kustomize/gateway/internal-gateway-api.yaml, kustomize/gateway/kustomization.yaml, kustomize/gateway/prometheus-routes.yaml
This patch adds the common gateway (flex-gateway) in nginx-gateway namespace. This gateway will be shared by all other namespaces to expose services internally. To do so the service that is getting exposed internally simply need to follow the fqdn naming of *.sjc.ohthree.com and ref the flex-gateway.
Also, adding the http routes for prometheus and alertmanager that use the above method to expose the two services internally.
=> Adds gateway to expose internal services

kustomize/skyline/base/deployment-apiserver.yaml
They broke something in latest that prevents skyline from doing a db-sync. If you roll back the image to tag 2023.1 it works again.
=> Skyline fix for dbsync

scripts/genestack.rc
This change will assert that the product is defined and in the event that the product is missing the RC file will raise an error instead of allowing the process to continue with an assumed product option.
=> fix: Remove product assumption when running the deployment

mkdocs.yml
The postgres install references keystone secrets which aren't in place during infrastructure installations.
The document is now packaged into a metering setion to bundle postgres and ceilometer
=> Move postgest into a metering section

docs/infrastructure-ingress.md, kustomize/ingress/external/helm/ingress-helm-overrides.yaml, kustomize/ingress/grafana/helm/ingress-helm-overrides.yaml, kustomize/ingress/internal/helm/ingress-helm-overrides.yaml
This change updates our worker process so that it has a base value of 4. The worker processes used to be "auto" which would create 1 process per core on the node. On production hardware this would result in at least 64 process and 32 threads per porc, totally 2048 threads. This change is simply enforcing a sane limit, and documenting how we can patch a new value into our environment when it's required.
=> fix: limit ingress worker processes

kustomize/rabbitmq-cluster/base/rabbitmq-cluster.yaml
We need the pods to not land on the same host
during scheduling. This enables the antiaffinity
rule to make sure that pods always land on different hosts.
JIRA: OSPC-389
=> Enables rabbitmq anti affinity rule

kustomize/rabbitmq-cluster/base/rabbitmq-cluster.yaml
Since we are using persistent messages, we need bigger storage to ensure that in times of high volume messages we have enough storage to handle it.
=> Change Rabbitmq storage to 20g

.github/workflows/kustomize-etcd-backups.yaml, Containerfiles/etcd-backup/Containerfile, Containerfiles/etcd-backup/backup.py, docs/etcd-backup.md, kustomize/backups/etcd/etcd-backup.yaml, kustomize/backups/etcd/kustomization.yaml, mkdocs.yml
This patch adds etcd backup cronjob with frequency of every 3 hours.
=> Adds etcd backup job

kustomize/rabbitmq-cluster/aio/kustomization.yaml, kustomize/rabbitmq-cluster/base/rabbitmq-cluster.yaml
The rabbitmq operator has recommendation that the memory request and limit be the same. This patch ensures that we request 10G memory and also have a 10G limit.
=> Ensures memory request and limit is same for rabbitmq

ansible/roles/host_setup/defaults/main.yml
This alleviates the inotify errors seen on many nodes in a K8s cluster when there are too many open files.
fs.inotify.max_user_instances works in conjunction with fs.inotify.max_user_watches. We have already updated the default for fs.inotify.max_user_watches
Example error without updating fs.inotify.max_user_instances:
systemctl restart systemd-resolved.service 
Failed to allocate directory watch: Too many open files
=> SET fs.inotify.max_user_instances=8192 instead of default 128

docs/infrastructure-letsencrypt.md, helm-configs/prod-example-openstack-overrides.yaml, kustomize/cinder/letsencrypt/kustomization.yaml, kustomize/glance/letsencrypt/kustomization.yaml, kustomize/heat/letsencrypt/kustomization.yaml, kustomize/horizon/letsencrypt/kustomization.yaml, kustomize/keystone/letsencrypt/kustomization.yaml, kustomize/neutron/letsencrypt/kustomization.yaml, kustomize/nova/letsencrypt/kustomization.yaml, kustomize/octavia/letsencrypt/kustomization.yaml, kustomize/placement/letsencrypt/kustomization.yaml, kustomize/skyline/letsencrypt/kustomization.yaml, mkdocs.yml
When using letsencrypt, you must annotate the named ingress with the letsencrypt cluster-issuer as well as any other desired acme.cert-manager.io annotations [1]. As most services have multiple ingresses (external vs internal), we must only annotate the ingress that will be accessed externally, else the ACME solver will not work correctly.
Using this optional overlay will help ensure the expected ingress is annotated. So that the challenge url is accessible externally.
1. https://cert-manager.io/docs/usage/ingress/#supported-annotations
=> Add optional kustomize letsencrypt overlay

docs/infrastructure-loki.md
Grafana has updated loki software and helm charts and is incompatible with current configuration examples.  Documenting the version of the loki helm chart to install.
=> Specify version of loki helm chart

ansible/roles/host_setup/defaults/main.yml
Adds additional sysctl options to help resolve NETDEV WATCHDOG timeouts.
Related: https://access.redhat.com/solutions/7028690
=> fix: assist with Intel ice driver NETDEV WATCHDOG timeouts

kustomize/mariadb-cluster/base/mariadb-galera.yaml, kustomize/mariadb-cluster/base/mariadb-maxscale.yaml
AntiAffinity is enabled but the rule does not get set on the statefulsets as expected. Adding the rule manually to prevent the maria pods from coming up on the same node(s).
Possibly fixed upstream in an upcoming release:
- [f86606162be96e7a36015037491c07747042efcf](https://github.com/mariadb-operator/mariadb-operator/commit/f86606162be96e7a36015037491c07747042efcf)
=> fix: Add podAntiAffinity rule for maria pods

docs/infrastructure-mariadb-ops.md, docs/k8s-kubespray.md
Without adding the hostname to /etc/hosts, we introduce slowness during privlege escalation (due to a DNS timeout). This additional command idempotently adds the hostname to /etc/hosts at the end of the line beginning with 127.0.0.1.
=> Doc improvements

.github/workflows/release-nova-uefi.yml, .github/workflows/smoke-nova-uefi.yml, Containerfiles/NovaEFI-Containerfile
Fix resolve issues with oslo-db by building in the supported
release of oslo db using the branch instead of the assumed
package release.
Related-Fix: https://github.com/openstack/oslo.db/commit/be0515daa260811ad77b5eb5b78670c77eda2df6
Co-Authored-By Luke Repko <luke.repko@rackspace.com>
=> feat: add oslo db dependency into nova-efi

helm-configs/fluentbit/fluentbit-helm-overrides.yaml
This enables the fluentbit service monitor fluentbit metrics in prometheus
=> Enable servicemonitor in fluentbit helm config

docs/openstack-cinder.md, docs/openstack-compute-kit.md, docs/openstack-glance.md, docs/openstack-heat.md, docs/openstack-keystone.md, docs/openstack-octavia.md
The mariadb-galera-primary VIP only sends traffic to the primary node in the cluster whereas mariadb-galera-secondary VIP load-balances the secondary nodes (good for read-only ops).
Ideally we would enable this in the helm chart, but the existing charts do not seem to know about this parameter. If the hostname can be constructed from what we have in kubectl, that would be better.
=> feat: configure database slave_connection param

docs/openstack-compute-kit.md, helm-configs/nova/nova-helm-overrides.yaml, kustomize/libvirt/helm/libvirt-helm-overrides.yaml
This is to enable ssh for nova compute pods to support migrations. Creating an ed25519 keypair for security and performance. Also a tweak to the daemonsets nova-compute-default and libvirt daemonsets is being made to set max_unavailable to a sane percentage of nodes in lieu of just 1 which may result in deployment times far exceeding the default timeout value in large environments.
=> feat: enable nova-ssh and tweak daemonsets

docs/infrastructure-libvirt.md
On the nodes, the `virsh` command will not exist unless we install the libvirt client. We can use the libvirt pod to execute the `virsh` command.
=> Fix command to validate libvirt

ansible/inventory/openstack-flex/inventory.yaml.example
we need to keep the cluster name to cluster.local otherwise all the helm install commands will need to modified accordingly to include the new cluster name. This also includes modifying the operator configs for infrastructure services like rabbitmq and mariadb
=> set the cluster_name variable to cluster.local in the example inventory for openstack-flex product

docs/storage-swift-object-store.md
Removed requirements because it said "TBD: FIXME" I have reached out to Derek Moyes on what should be put in there, but I do not think that should be in our public facing docs.
=> DOC: Removed place holder text

docs/infrastructure-letsencrypt.md, helm-configs/prod-example-openstack-overrides.yaml
As we are patching the ingress resource using kustomize, we can skip the details in helm.
=> Fix an example to use letsencrypt for certificate

helm-configs/cinder/cinder-helm-overrides.yaml, helm-configs/glance/glance-helm-overrides.yaml, helm-configs/heat/heat-helm-overrides.yaml, helm-configs/keystone/keystone-helm-overrides.yaml, helm-configs/lab-overrides.yaml, helm-configs/neutron/neutron-helm-overrides.yaml, helm-configs/nova/nova-helm-overrides.yaml
We define the use of quorum queues via kustomize as the default queue type for the named vhosts, but the oslo_messaging_rabbit config opt of `rabbit_ha_queues: true` was set, taking precedence. We actually do not want to use HA (mirrored) queues, as they are being deprecated, and will be removed in newer versions of RMQ (4.x being released EOY 2024). The use of HA queues in genestack up to this point was the result of sane but no longer ideal defaults set by openstack-helm that were carried forth.
This explicitly disables rabbit_ha_queues, and then enables rabbit_quorum_queue. **Removing the related rabbit vhost is required for this change prior to re-deploying a given openstack service.**
Example of re-deploying nova when making this change; note how we remove the queue, vhost, and user: …
=> fix: use rabbit quorum queues in lieu of ha

kustomize/ingress/external/helm/ingress-helm-overrides.yaml, kustomize/ingress/internal/helm/ingress-helm-overrides.yaml, kustomize/topolvm/general/kustomization.yaml
- We are using https://kubernetes.github.io/ingress-nginx helm chart to deploy ingress-nginx. But it seems the values.yaml used is for different chart. This commit updates the values.yaml file of internal and external ingress-nginx helm chart used for the deployment. 
- Additionally, it specifies the MetalLB annotation to use the external metallb IP address pool for the external ingress service.
=> Fix Helm values.yaml for internal and external ingress-nginx Helm chart

ansible/playbooks/network-service-types.yaml, justfile
In particular, we want to set some service types for all subnets of PUBLICNET to disallow instances from creating a server with a port on the PUBLICNET, so that they have to use floating IPs, and the playbook run defaults to that network and the service types to enforce that.
JIRA:OSPC-474
=> Add playbook to set uniform service types for all subnets of a network.

requirements.txt
There is a dependabot alert on jinja2 version.
We need this updated to 3.1.4
Ref: https://github.com/rackerlabs/genestack/security/dependabot/8
=> Update jinja2 to 3.1.4

helm-configs.example/glance/glance-helm-overrides.yaml
This provides the options to move the glance store to swift. We leave the default value to pvc so as
not to break existing deployments accidently. Howerver, providing a override on the helm command to --storage=pvc will deploy a glance with pvc backend.
These values should be overwritten in your region
specific secrets file to ensure no mistake.
=> Switches glance store backend to swift

bin/create-secrets.sh
This commit fixes genestack issue https://github.com/rackerlabs/genestack/issues/340 to remove trailing newline (\n) from the base64 secrets
I have tested the modifications in my lab and the resulting secret.yaml file could be applied and secrets were created without any issue
=> genestack issue #340 trailing newline characters for base64 secret

helm-configs.example/nova/nova-helm-overrides.yaml
Switch cpu_model = host-model which uses the model from libvirt cpu_map that most closly matches the host and requests additional cpu flags to complete the match.
We need this to make live-migration work in rackspace env. For more info on cpu_modes see openstack docs on CPU models.
=> Switches cpu_model to host-model

base-kustomize/kustomize.sh
Uses GENESTACK_KUSTOMIZE_ARG environment variable. Still allows for using a cli argument for kustomize.sh script
=> Allows use of environment variable in kustomize.sh

bin/create-secrets.sh, docs/infrastructure-namespace.md
We already have a secrets.yaml in several regions at this location in the repository we store genestack configurations. To avoid confusion and the possibility of that being overwritten, let's rename this newly added secrets file.
Considering the sensitivty of the secrets therein, let's take away global read perms too.
=> fix: rename generated secrets file and fix perms

ansible/roles/host_setup/vars/debian.yml, ansible/roles/host_setup/vars/ubuntu.yml
Debian needs systemd-timesyncd to be installed by default to support kubespray when deploying with NFS.
> To make it easier to see what packages we have installed the lists
have been sorted.
=> fix: add missing package for debian

docs/ovn-monitoring-introduction.md
This seems good to mention, since _Genestack_ will have a non-zero count for an otherwise bad looking metric during normal operation, and the _Kube-OVN_ docs actually say *very* little about this metric.
=> doc: discuss `pinger_inconsistent_port_binding` metric for _Kube-OVN_

base-helm-configs/ceilometer/ceilometer-helm-overrides.yaml
These allow us to quickly distinguish whether an image is linux or windows, the distro, and version. Useful for analytics.
=> feat: include additional attrs on image resources

docs/grafana.md, docs/octavia-loadbalancer-setup-guide.md, mkdocs.yml
- Added documentation on how to create a load balancer using the CLI
- Fixed a typo in grafana deployment doc.  It was missing the keyword `apply`
=> docs: added clb guide and fixed typo in grafana doc

base-helm-configs/ceilometer/ceilometer-helm-overrides.yaml
The cinder trait for instance_id being parsed out was trying to get the instance id from `payload.volume_attachment[0].server_id` but upon inspection of the raw messages emitted from cinder arriving via RMQ, it's clear that key is actually, `instance_uuid`, not `server_id`.
Now, when cinder messages traverse ceilometer, instance uuid is populated as expected. We don't have to wait for the pollster to run.
Furthermore, explicitly define event_create and event_update on the gnocchi volume resource to look out for volume create/attach events resepectively, to keep the resouce up-to-date in gnocchi in near real-time.
=> fix(ceilometer): update json path to vm uuid

base-kustomize/prometheus/values.yaml
Handle Alertmanager installation using `nodeSelector`
=> fix(prometheus): remove node affinity for the alertmanager installation (#439)

base-helm-configs/ceilometer/ceilometer-helm-overrides.yaml, base-helm-configs/gnocchi/gnocchi-helm-overrides.yaml, base-kustomize/ceilometer/aio/kustomization.yaml, base-kustomize/ceilometer/base/hpa-ceilometer-notification.yaml, base-kustomize/ceilometer/base/kustomization.yaml, base-kustomize/gnocchi/aio/kustomization.yaml, base-kustomize/gnocchi/base/hpa-gnocchi-api.yaml, base-kustomize/gnocchi/base/kustomization.yaml, docs/openstack-ceilometer.md
This just adds the hpa configs to ceilometer and gnocchi. I tested each `aio` and `base` overlay in my lab to ensure the desired min replicas were achieved. I also tune the max_unavailable for related daemon-sets from 1 to 20% to speed up helm upgrade/installs.
=> feat(metering): add hpa config for aio/base overlays

Containerfiles/GnocchiRXT-Containerfile
Gnocchi resource job was failing because the gnocchi executable was not installed on the image.  `pip install gnochhiclient` will add the necessary executable.
=> fix: added gnocchiclient to allow resource cleaner job to execute

docs/openstack-compute-kit-neutron.md
=> doc: Add documentation on MTU settings for Neutron.

base-helm-configs/ceilometer/ceilometer-helm-overrides.yaml
Do not use the instance_type_id field as that seems to unreliably represent the flavor_id. From what I have observed, some messages come through as a numerical value (the idx of the flavor in the flavors table), and some messages come through with the uuid of the flavor.
fix(ceilometer): fix flavor_id extraction
Confirmed instnace_type_id comes through in messages as numerical index value while instance_flavor_id is what we really want.
fix(ceilometer): use payload.node for consistency
`host` is derived from the publisher id similar to `service`, which might be a compute api node in lieu of the actual compute hype. The node param under payload seems sticky to the hypervisor name, so defer to that in the gnocchi resource definition...
=> fix(ceilometer): tweak event_update processing

base-helm-configs/barbican/barbican-helm-overrides.yaml
- Barbican service endpoint is http://barbican-api.openstack.svc.cluster.local:9311
- With current configuration, accessing the internal endpoints tries to query `http://barbican.openstack.svc.cluster.local/v1/`:
```
+----------------------------------+-----------+--------------+--------------+---------+-----------+-------------------------------------------------------+
| ID                               | Region    | Service Name | Service Type | Enabled | Interface | URL                                                   |
+----------------------------------+-----------+--------------+--------------+---------+-----------+-------------------------------------------------------+
| 78c25951ce53408089edb1458216810f | RegionOne | barbican     | key-manager  | True    | internal  | …
```
=> Fix the barbican-api service endpoint in barbican.conf

ansible/playbooks/deploy-cinder-volumes-reference.yaml, docs/openstack-cinder-lvmisci.md
This change updates the cinder reference playbook so that it deploys cinder with only the backend configuration file that we expect, with a single idempotent transaction. This will improve the deployment experience and ensure that we're not running backends that don't make sense for the deployment.
=> feat: Update the cinder reference playbook

ansible/playbooks/deploy-cinder-volumes-reference.yaml
This change will enable the backend store to run with multiple backends on a deployment host. This will ensure that only the backends we expect to run are deployed.
=> feat: update the playbook to support multibackend store

base-kustomize/gateway/base/files/nginx.conf, base-kustomize/gateway/base/kustomization.yaml, base-kustomize/gateway/base/nginx-conf-override.yaml, docs/infrastructure-gateway-api.md
There is no easy way to add `proxy_buffer_size` or similar parameters to Nginx via CRD. A feature for the same is being worked on and might be released early November per [nginxinc/nginx-gateway-fabric/#1398](https://github.com/nginxinc/nginx-gateway-fabric/issues/1398#issuecomment-2274235810).
As a workaround, this change includes the default nginx configuration as deployed in the current version of nginx gateway fabric. It will be made available to the nginx pod at `/etc/nginx/nginx.conf` by supplanting the nginx-gateway deployment with a kustomize patch that overrides `nginx.conf` via a mounted configMap volume containing said file.
Several additional parameters, `proxy_buffer_size` and `proxy_buffers` are being included at this time, to account for some large header payloads being …
=> fix(gwapi): allow custom nginx.conf

ansible/playbooks/templates/genestack-multipath.conf
Just cleaning up spacing to be consistent on Linux AND Mac
=> spaces/tabs in genestack-multipath.conf

base-helm-configs/barbican/barbican-helm-overrides.yaml
Current public barbican endpoint does not resolve nor is there an listener on port 80, moving public endpoint to barbican-api and port 9311.
=> Update barbican-helm-overrides.yaml keystone endpoint

base-helm-configs/nova/nova-helm-overrides.yaml
This change adds three new nova options to ensure that new instances have up to 10 minutes to become active, even when using boot from volume.
=> fix: Ensure build timeouts are set to 10 minutes

base-kustomize/grafana/base/kustomization.yaml, base-kustomize/grafana/base/plugins.yaml
I did CHG0156370 and deployed Grafana to SJC. Both SJC and DFW need this `plugins.yaml` and to have it added to `kustomization.yaml` to most closely match the actual deployed state of both environments.
I think we should add this in here? I've created this PR for those more familiar with Grafana, camptocamp, etc. to evaluate and merge if it looks warranted.
=> feat: Add plugins.yaml for camptocamp for Grafana

base-kustomize/prometheus/alerting_rules.yaml, base-kustomize/prometheus/values.yaml
restores blackbox alerting rules and rabbitmq alert size from https://github.com/rackerlabs/genestack/commit/cb440e203a7d657bba5eb885f1522fc98542b6bb
which appears inadvertently removed in
https://github.com/rackerlabs/genestack/commit/3dfc4afcd397f1a155fcd39809704608b19df07b
JIRA:OSPC-689
=> fix: restore blackbox alerting rules and rabbitmq alert size

base-helm-configs/cinder/cinder-helm-overrides.yaml, base-helm-configs/neutron/neutron-helm-overrides.yaml, base-helm-configs/nova/nova-helm-overrides.yaml, docs/adding-new-node.md, docs/infrastructure-ovn-setup.md, docs/octavia-loadbalancer-setup-guide.md, docs/openstack-cinder-fips-encryption.md, docs/openstack-cinder-lvmisci.md
This change will ensure that Genestack operates with availability zones using common naming conventions by default. The AZ support is being added to Nova, Cinder, and Neutron.
=> feat: use AZs by default

base-kustomize/prometheus/alerting_rules.yaml
The letsencrypt integration should update certs within the ~30 day mark. Adjusting the alerts for that assumption. Also adjusting the rabbitmq alert as 25 queue count is way too low for any reasonably sized deployment.
=> Adjusting blackbox and rabit alerting rules

CONTRIBUTING.md
Add some context and more specificity to help potential commiters work with Genestack in an easier way.
Include references and links to conventional commit messages and signed/verified commits.
=> docs: Update CONTRIBUTING.md to give more context

base-helm-configs/monitoring/openstack-metrics-exporter/openstack-metrics-exporter-helm-overrides.yaml
The openstack metrics exporter is a heavy exporter by default. Any additional strain on the system causes timeouts to occur. This fix should eliminate the timeout failures.
=> Fix: Updating openstack metrics polling interval and timeout

docs/k8s-kubespray.md, docs/k8s-labels.md
The docs were changed to point to a playbook that is broken, this change updates the docs to ensure readers have a functional setup. The docs still have the broken references but they've been moved to experimental.
=> fix: update docs to be sure we have a functional build

base-helm-configs/cinder/cinder-helm-overrides.yaml, base-helm-configs/neutron/neutron-helm-overrides.yaml
This change updates default_availability_zones to ensure it has a default value. While this option is supposed to assume the value of the bound az, openstack helm returns a `<no value>` value which makes the services very upset. By setting a value we make the service happy, and we all want happy services.
=> fix: update default_availability_zones to a value

.github/workflows/kustomize-cinder-volume-netapp.yaml, base-kustomize/cinder/netapp/configmap-etc.yaml, base-kustomize/cinder/netapp/deploy-volume-netapp.yaml, base-kustomize/cinder/netapp/hpa-cinder-volume-netapp.yaml, base-kustomize/cinder/netapp/kustomization.yaml, docs/openstack-cinder-netapp.md, mkdocs.yml
This creates a new Kustomize deployment for cinder with a netapp volume
backend. The worker uses an existing cinder deployment managed by helm
kustomizes the configuration values and produces a netapp specific volume
container which has the ability to run with multiple netapp backends.
To use this container the following secrete must be created
``` shell
kubectl --namespace openstack \
create secret generic cinder-netapp \
--type Opaque \
--from-literal=BACKENDS="netapp-backend-1,root,10.0.0.1,80,vserver1,qos-something,True,True,True,True,enabled"
```
Each backend has 11 values which correspond to the needed configuration.
Multiple backends are supported using a semicolon.
=> feat: netapp-volume-worker support

base-kustomize/mariadb-cluster/base/mariadb-backup.yaml
The mariadb-backup init container already runs as root and tries to chmod `777` the backup files, but they get changed back to `0644` at some point later on. This results in the mariadb-operator pod running into a permission denied situation during its cleanup for the desired retention setting.
The fix herein simply runs the pod as root so that the mariadb-operator container in the pod has access to cleanup the old backups as needed.
This change fixes **NEW** backups, existing ones need to have the corresponding `CronJob` modified (see below).
While re-applying the `mariadb-backup` will update the existing `Backup`, the mariadb-operator does not seem to reconcile the `CronJob` for the securityContext attribute. One must update the `CronJob` manually or apply a patch to fix existing jobs …
=> fix: OSPC-613 mariadb cleanup old backups

ansible/playbooks/deploy-cinder-netapp-volumes-reference.yaml, ansible/playbooks/templates/cinder-volume-netapp.service, base-kustomize/cinder/netapp/deploy-volume-netapp.yaml, base-kustomize/cinder/netapp/kustomization.yaml, docs/openstack-cinder-netapp-container.md, docs/openstack-cinder-netapp-worker.md, mkdocs.yml
This change adds a cinder volume netapp playbook to support running the cinder-volume service on baremetal, for the specific purpose of supporting netapp backends.
This change resolves defect OSPC-802 which was discovered in testing. With this change implemented, NetApp backends will be able to operate both data and bootable volumes.
Issue: https://rackspace.atlassian.net/browse/OSPC-802
=> fix: Add cinder volume netapp playbook

docs/prometheus.md
release name went from prometheus to kube-prometheus stack here: https://github.com/rackerlabs/genestack/commit/a468178df47062aa2a9d5367e44cabbbdf3d2db5
=> doc: Fix Prometheus post-checking command in docs to match release name

docs/openstack-resource-lookups.md, mkdocs.yml
This change creates a new doc page highlighting how a cloud administrator can lookup account information from a resource ID.
Resolves: https://rackspace.atlassian.net/browse/OSPC-739
=> feat: Create documentation on resource lookups

.github/workflows/mkdocs.yaml
There was a bug that would not run the publishing job if the file mkdocs.yml was modified, this fixes that.
=> fix: resolve publishing bug

base-kustomize/grafana/base/grafana-database.yaml
All of the grants are prefixed with the service name, found grafana missing this convention so fixing it for style and to prevent confusion.
=> fix(grafana): change grant name to grafana-grant

docs/infrastructure-gateway-api.md
The gateway docs reference flags that don't work, this change updates the docs to fix those broken references.
=> fix: gateway docs

docs/infrastructure-ovn-setup.md, docs/ovn-kube-ovn-openstack.md, mkdocs.yml
This change adds docs to highlight how we run updates to the environment when making changes to the ovn environment, for use with OpenStack.
=> feat: add ops docs for ovn-to-openstack updates

bin/install-libvirt.sh, bin/install-memcached.sh, bin/install-postgres-operator.sh, bin/install-skyline.sh, bin/setup-openstack.sh
This change updates the scripts to allow for user input where needed.
=> fix: add $@ to scripts where needed

bin/install-gnocchi.sh
The Postgres operator installs the admin password into this secret. The old secret reference was from when installs were being done using openstack-helm-infra.
=> fix(gnocchi): pg admin password ref new secret

ansible/inventory/genestack/group_vars/k8s_cluster/addons.yml, ansible/inventory/genestack/group_vars/k8s_cluster/k8s-cluster.yml, docs/k8s-kubespray-upgrade.md, requirements.txt
This change retains support for our current version of Kubernetes but also ensures that we have future support for upgrades as needed.
=> feat: update kubespray to v2.26.0

base-kustomize/mariadb-cluster/base/mariadb-replication.yaml
During testing, it was found that we are not applying affinity / anti-affinity to the mariadb-cluster pods.  This pr enforces affinity and anti-affinity to only allow db pods to de scheduled to worker nodes.
=> ensure db pods live on seperate worker nodes

manifests/metallb/metallb-openstack-service-lb.yml
The pool name we were setting doesn't match the nginx-gateway reference. This change makes them match.
=> fix: resolve gateway-api-external reference

docs/openstack-neutron-networks.md
This change removes the old "nova" availability zone reference.
=> fix: remove nova az reference

base-kustomize/mariadb-cluster/base/mariadb-replication.yaml
Currently anti-affinity is not supported by our version of the mariadb CRD.  This pr disables anti-affinity by commented it out until such time as we can update the version of the CRD we are using.
=> disable antiaffintiy as its not currently supported

ansible/inventory/genestack/group_vars/k8s_cluster/k8s-cluster.yml
This change was implemented to ensure that we're deploying a recent version of k8s by default.
Co-Authored-By: Luke Repko <luke.repko@rackspace.com>
=> feat: Update k8s to the latest 1.30.4

base-kustomize/mariadb-cluster/base/mariadb-backup.yaml, base-kustomize/mariadb-cluster/base/mariadb-replication.yaml, bin/install-mariadb-operator.sh
This change takes our build of mariadb to the latest stable release.
Co-Authored-By Luke Repko <luke.repko@rackspace.com>
=> feat: update mariadb to the latest stable release

ansible/playbooks/deploy-cinder-volumes-reference.yaml
Restarting tgt should never be done on a storage node exporting targets.  Instead, use reload on and tgt conf.d change.
=> move tgt restart to tgt reload on etc/tgt/conf.d/cinder.conf change

base-helm-configs/cinder/cinder-helm-overrides.yaml
By default the barbican client in cinder uses `public`, but that is not ideal for communication between cinder and barbican in a local cluster. Update this to be internal, as public comms might not work in some environments by design.
=> fix: Use internal barbican endpoint type

ansible/roles/host_setup/tasks/CPU_frequency.yml, ansible/roles/host_setup/tasks/main.yml, ansible/roles/host_setup/tasks/pin_kernel.yml, ansible/roles/host_setup/vars/debian.yml, ansible/roles/host_setup/vars/ubuntu.yml
https://rackspace.atlassian.net/browse/OSPC-979
- Switch to TuneD:
- Replaces cpupower with TuneD to handle CPU governor settings.
- Applies the throughput-performance profile for enhanced system performance.
- ```
throughput-performance
Profile for typical throughput performance tuning. Disables power saving mechanisms
and  enables  sysctl  settings that improve the throughput performance of your disk
and network IO. CPU governor is set to performance and CPU energy performance  bias
is set to performance. Disk readahead values are increased.
```
- Ensures TuneD is installed, enabled.
- Kernel Version Management:
- Checks and validates kernel version, failing if it’s below the required version.
- Pins kernel packages to prevent automatic upgrades that could disrupt stability.
- …
=> OS Standardization: Kernel, Power, and Update Policies

base-helm-configs/nova/nova-helm-overrides.yaml
1. block_device_allocate_retries count increased from 120 to 180, to give more time for volume creation from large images, without getting timed out.
2. instance_build_timeout increased from 600 to 900, to give more time for Instance creation from large images, without getting timed out.
=> OSPC-202: Increase timeout for instance volume creation

base-helm-configs/keystone/keystone-helm-overrides.yaml
This change updates the heartbeat value to match all other services
Fixes: https://github.com/rackerlabs/genestack/issues/662
=> fix: resolve null value

docs/k8s-config.md
This plugin is used to help operators maintain OVN deployments.
=> feat: document the deployment of the KO plugin

base-helm-configs/nginx-gateway-fabric/helm-overrides.yaml
this PR is raised to modify the annotation in the nginx-gateway-fabric service to the gateway-api-external pool in metallb
=> modify the annotation for the nginx-gateway-fabric to gateway-api-external

ansible-collection-requirements.yml, ansible/roles/host_setup/defaults/main.yml, ansible/roles/host_setup/handlers/main.yml, ansible/roles/host_setup/tasks/main.yml, ansible/roles/host_setup/templates/modprobe.conf.j2, ansible/roles/host_setup/templates/sysstat.cron.debian.j2, ansible/roles/host_setup/templates/sysstat.default.j2, ansible/roles/host_setup/templates/systemd-environment.j2
The config-template module, while useful, wasn't being used, so we removed it.
=> fix: remove config-template

base-helm-configs/keystone/keystone-helm-overrides.yaml
Resolves error when token size generation exceeds 255.
``` log
2025-01-25 20:30:24.489983 2025-01-25 20:30:24.489 9 INFO keystone.token.token_formatters [None req-03c07355-b705-4591-bcc2-1dcf172ec5c0 5cc1aa7e42870935a560cf436ec7faed59981b4585e84993c56c4fc49edfe705 870adeaf387f4ad68f179dc989721269 - - c82f424b9db24fb4a86cb80359c6211f c82f424b9db24fb4a86cb80359c6211f] Fernet token created with length of 268 characters, which exceeds 255 characters
```
This change simply sets the limit to 300 as recommended when using other federation providers.
=> fix: resolve token size error

base-helm-configs/memcached/memcached-helm-overrides.yaml
This change updates our memcached values file, without this change memcached is running stock settings, with only 64M of cache, 4 threads, and a very limited number of allowed connections. This adjusts the settings to run with known good configurations and documents how operators can change the values as needed.
=> fix: memcached size limits

Containerfiles/NovaEFI-Containerfile, ansible/roles/host_setup/vars/debian.yml, ansible/roles/host_setup/vars/ubuntu.yml
os-brick requires nvme-cli to be installed otherwise it throws warnings
``` log
2025-01-26 01:21:49.169 3229256 WARNING os_brick.privileged.nvmeof [-] Could not generate host nqn: [Errno 2] No such file or directory: 'nvme'
```
This change simply ensures that the tool is installed on our hosts by default.
=> fix: add nvme-cli as a base package

ansible/playbooks/host-setup.yml
The host setup playbook anchored on all, and then made specific tasks execute on special group names. This change simply updates the inital playbook so that it can run on any invntory and will execute post tasks when special variables are defined.
=> fix: update host setup so that it will respect different inv files

ansible/roles/host_setup/files/queue_max.service, ansible/roles/host_setup/files/queue_max.sh, ansible/roles/host_setup/handlers/main.yml, ansible/roles/host_setup/tasks/configure_hosts.yml
Implement the service one shot for automatically setting the queue max.
Related Issue: https://rackspace.atlassian.net/browse/OSPC-832
=> fix: Add oneshot service for queue max handling

docs/infrastructure-mariadb-ops.md
With the new mysql client, dumping database tables without --column-statistics=0 will result in an error and a busted backup.  Update the docs to include the correct flags when backing up a single vs all of the databases.
=> docs: column-statistics needs to be set to 0

ansible/playbooks/host-setup.yml
when /etc/multipath.conf has been changed, we restart multipathd.  we also need to restart the multipath-tools service.
=> fix (multipath-tools): restart when etc/multipath.conf is changed

ansible/playbooks/host-setup.yml
Orignally i had intended to have seperate handlers for multipathd and multipath-tools thinking there might be a time we want to restart either service.  After reviewing the playbook, we will want to restart both services on any etc/muiltipath.conf change.  No need for seperate handlers.  This PR consolidates both service restarts into a single handler.
=> fix (multipath): consolidate restarts to single handler

docs/accelerated-computing-infrastructure.md, docs/adding-new-node.md, docs/alerting-info.md, docs/api-status.md, docs/documentation-standards.md, docs/etcd-backup.md, docs/genestack-logging.md, docs/genestack-upgrade.md, docs/grafana.md, docs/index.md, docs/infrastructure-gateway-api-custom.md, docs/infrastructure-mariadb.md, docs/infrastructure-memcached.md, etc/gateway-api/listeners/grafana-https.json, etc/gateway-api/listeners/loki-https.json, etc/gateway-api/routes/custom-grafana-routes.yaml, etc/gateway-api/routes/custom-loki-internal-routes.yaml
added grafana / loki listener patches to base as well as route examples.  Expanded on the grafana doc to include a Listener and Route section that redirects back to the Gateway API docs if needing to patch the nginx-gateway or add a httproute.  Also ran the docs through a linter.
=> grafana and other doc updates

ansible/inventory/genestack/group_vars/k8s_cluster/k8s-net-kube-ovn.yml
This change sets the kube-ovn version to the latest release within the stable 1.12.x series. By setting this option we're ensuring there's no drift in how our system is deployed and performs, even if the underlying version of kubespray or kubernetes changes.
=> chore: set the kube-ovn version

base-kustomize/barbican/base/hpa-barbican-api.yaml, base-kustomize/ceilometer/base/hpa-ceilometer-notification.yaml, base-kustomize/cinder/base/hpa-cinder-api.yaml, base-kustomize/cinder/base/hpa-cinder-scheduler.yaml, base-kustomize/glance/base/hpa-glance-api.yaml, base-kustomize/gnocchi/base/hpa-gnocchi-api.yaml, base-kustomize/heat/base/hpa-heat-api.yaml, base-kustomize/heat/base/hpa-heat-cfn.yaml, base-kustomize/heat/base/hpa-heat-engine.yaml, base-kustomize/horizon/base/hpa-horizon-api.yaml, base-kustomize/keystone/base/hpa-keystone-api.yaml, base-kustomize/magnum/base/hpa-magnum-api.yaml, base-kustomize/magnum/base/hpa-magnum-conductor.yaml, base-kustomize/neutron/base/hpa-neutron-server.yaml, base-kustomize/nova/base/hpa-nova-api-metadata.yaml, base-kustomize/nova/base/hpa-nova-api-osapi.yaml, base-kustomize/nova/base/hpa-nova-conductor.yaml, base-kustomize/nova/base/hpa-nova-novncproxy.yaml, base-kustomize/nova/base/hpa-nova-scheduler.yaml, base-kustomize/octavia/base/hpa-octavia-api.yaml, base-kustomize/octavia/base/hpa-octavia-worker.yaml, base-kustomize/placement/base/hpa-placement-api.yaml, base-kustomize/skyline/base/hpa-skyline-apiserver.yaml
This change is removing the CPU HPA metric. This metric is unused in our deployments, so the setup is at best doing nothing and at worst creating load that doesn't need to be there.
Common deployment
``` shell
NAME                      REFERENCE                            TARGETS                                            MINPODS   MAXPODS   REPLICAS   AGE
barbican-api              Deployment/barbican-api              cpu: <unknown>/50%, memory: 119750656/500Mi        3         9         3          38d
ceilometer-notification   Deployment/ceilometer-notification   cpu: <unknown>/50%, memory: 122153642666m/500Mi    3         9         3          2d12h
cinder-api                Deployment/cinder-api                cpu: <unknown>/50%, memory: 575287296/500Mi        3         9         4 …
```
=> chore: update hpa settings

bin/install-fluentbit.sh, bin/install-grafana.sh, bin/install-libvirt.sh, bin/install-mariadb-operator.sh, bin/install-memcached.sh, bin/install-postgres-operator.sh
When appending command line args to the scripts, we need to ensure we include a space between the HELM_CMD and the args being appended.
=> fix: (install scripts) include space in HELM_CMD additional args

base-helm-configs/grafana/azure-overrides.yaml.example
During testing we found extraSecretMounts doesn't merge arrays, instead it replace it when in any helm file. This change updates the azure example so that it has all required items.
=> fix: azure integration extraSecretMounts

base-helm-configs/neutron/neutron-helm-overrides.yaml
Unfortunately all worker processes have a 'reported_hosts' set to
remember from which host it has seen agent reports already. But right
after a server start when that set is still empty, each worker will
unconditionally write the received physnet-segment information into
the db. This means we multiply the load on the db and rpc workers by
a factor of the rpc worker count.
=> fix: tunedown neutron rpcworkers

base-helm-configs/keystone/keystone-helm-overrides.yaml
This change is needed so that skyline can report on user assigned roles from the dashboard.
=> feat: add policy so users can see their assigned roles

base-helm-configs/glance/glance-helm-overrides.yaml
This change allows admin and image-services to manage images, even in a multi-tenant image store environment.
=> fix: add the ability for the system to manage images

base-helm-configs/cinder/cinder-helm-overrides.yaml
Use the RXTLVM driver as default driver.  Users still have the ability to override in etc/genestack/helm-configs/cinder
=> feat: use rxtlvm and default cinder driver

ansible/inventory/genestack/group_vars/k8s_cluster/k8s-cluster.yml
We need to ensure that our environment is able to grow and scale by default. This change updates our clusters ip space so that we have room to grow.
=> fix: update our default network space

base-helm-configs/barbican/barbican-helm-overrides.yaml
This change ensures that barbican is started with multiple processes.
=> fix: Barbican only has one worker

ansible/playbooks/host-setup.yml
This change will disable multipath when custom_multipath is not enabled. This is being done because ubuntu ships with multipath installed and configured by default and while that can be helpful, it can also cause issues with systems.
This change will ensure that our platform is using the right services when they're enabled.
=> fix: disable multipath when it's not used

ansible/inventory/genestack/group_vars/all/all.yml, ansible/roles/host_setup/defaults/main.yml, ansible/roles/host_setup/handlers/main.yml, ansible/roles/host_setup/tasks/configure_hosts.yml, ansible/roles/host_setup/tasks/main.yml, ansible/roles/host_setup/templates/timesyncd.conf.j2, ansible/roles/host_setup/vars/ubuntu.yml, docs/openstack-data-disk-recovery.md
=> chore: add disk reference to the recovery docs

ansible/inventory/genestack/group_vars/k8s_cluster/k8s-cluster.yml
The pod assignment network defaults we had created an overlap which could result in systemic failure. This change adjusts the deafult values so that there's no chance of overlap.
=> fix: adjust the default network for pods

base-kustomize/gateway/base/files/nginx.conf, docs/infrastructure-gateway-api.md
There is a patch in the `base` overlay which modifies proxy_buffers to account for large headers which is common in our envioronment and ultimately results in Nginx throwing a 502 and logging an error like, "upstream sent too big header while reading response header from upstream".
This update also includes the latest changes to the nginx.conf as obtained from a fresh install.
Starting in v1.5.0, the SnippetsFilterAPI was added which can be used in lieu of this configuration override, though it has to be enabled manually, and more testing is needed to implement the same.
Jira: OSPC-990
PR: #463
=> docs: Use kustomize overlay for Nginx GW API

ansible/playbooks/custom_exporters.yml, ansible/playbooks/extra/custom_exporters/perccli.py, ansible/playbooks/extra/custom_exporters/requirements.txt
Adds virtualenv for custom exporters in venv:
-   pip installs prometheus_client in venv
-   Moved crons from crontab to /etc/cron.d/flex-prometheus-exporters
-   Cron jobs utilizing python exporters successfully utilize venv
Adds the following python custom exporters:
- perccli MegaRAID DELL controller, LD, VD, PD, BBU status/health
- ssacli HP RAID controller, LD, VD, PD statuses/health
Adds the following script/sh/bash exporters:
-   md Linux software RAID details
-   multipathd device mapper, device, and path status/health
-   nvme-cli data and status/health specific to NVME
ALL data confirmed to be hitting Prometheus and is available
to craft dashboards, rules, alerts and eventually automation.
=> Feat: Updated Prometheus custom exporters for virtualenv

ansible/playbooks/host-setup.yml
While the playbook assumes that multipath is installed, there is a possibility that it is not. This change ensures that even when mp is being disabled that we don't fail in the event the services are not setup.
=> fix: add ignore errors

base-kustomize/barbican/base/barbican-mariadb-database.yaml, base-kustomize/barbican/base/barbican-rabbitmq-queue.yaml, base-kustomize/ceilometer/base/ceilometer-rabbitmq-queue.yaml, base-kustomize/cinder/base/cinder-mariadb-database.yaml, base-kustomize/cinder/base/cinder-rabbitmq-queue.yaml, base-kustomize/designate/base/designate-mariadb-database.yaml, base-kustomize/designate/base/designate-rabbitmq-queue.yaml, base-kustomize/glance/base/glance-mariadb-database.yaml, base-kustomize/glance/base/glance-rabbitmq-queue.yaml, base-kustomize/grafana/base/grafana-database.yaml, base-kustomize/heat/base/heat-mariadb-database.yaml, base-kustomize/horizon/base/horizon-mariadb-database.yaml, base-kustomize/keystone/base/keystone-mariadb-database.yaml, base-kustomize/keystone/base/keystone-rabbitmq-queue.yaml, base-kustomize/magnum/base/magnum-mariadb-database.yaml, base-kustomize/magnum/base/magnum-rabbitmq-queue.yaml, base-kustomize/neutron/base/neutron-mariadb-database.yaml, base-kustomize/neutron/base/neutron-rabbitmq-queue.yaml, base-kustomize/nova/base/nova-mariadb-database.yaml, base-kustomize/nova/base/nova-rabbitmq-queue.yaml, base-kustomize/octavia/base/octavia-mariadb-database.yaml, base-kustomize/octavia/base/octavia-rabbitmq-queue.yaml, base-kustomize/placement/base/placement-mariadb-database.yaml, mkdocs.yml
This change ensures that helm annotations are always used, even if a given manifest is applied directly. This is useful for support when uninstalling/installing services.
=> chore: add helm annotations to kustomize

bin/install-fluentbit.sh, bin/install-grafana.sh, bin/install-libvirt.sh, bin/install-mariadb-operator.sh, bin/install-memcached.sh, bin/install-postgres-operator.sh, bin/install-prometheus.sh, bin/install-template.sh, scripts/convert_osa_inventory.py
The scripts were all using "$*" for user includes but that wasn't working. So this change makes the linter happy and ensures that users are able to extend the flags used within a script by setting $@ at the end.
=> chore: bin/scripts cleanup

bin/install-fluentbit.sh, bin/install-grafana.sh, docs/grafana.md, docs/infrastructure-fluentbit.md
The helm repo update / add functions were documented but not part of our install sciprts. This change ensures that the repos are now part of the scripts and not a specific documentation step for FluentBit and Grafana.
=> chore: move the helm repo update/add to scripts

base-helm-configs/longhorn/longhorn-helm-overrides.yaml, bin/install-longhorn.sh, docs/storage-ceph-rook-internal.md, docs/storage-longhorn.md, manifests/longhorn/longhorn-encrypted-storageclass.yaml, manifests/longhorn/longhorn-general-storageclass.yaml, manifests/longhorn/longhorn-namespace.yaml
This change moves a lot of the longhorn examples into files so that they can be used without having to copy and paste.
Additionally, the node pre work section was removed because all required steps are now covered by our host-setup playbook.
=> chore: cleanup longhorn docs

base-helm-configs/ceilometer/ceilometer-helm-overrides.yaml
Ceilometer does not actually need this to function properly anymore. It used to have an API but was deprecated a while back. Creating a service in keystone for it is mostly harmless but results in WARNING level logs in other services when they do a service list, find ceilometer in the output, but no related keystone endpoint exists.
=> fix(ceilometer): Disable the ks_service job

base-helm-configs/barbican/barbican-helm-overrides.yaml, base-helm-configs/heat/heat-helm-overrides.yaml, base-helm-configs/octavia/octavia-helm-overrides.yaml
This change resolves a keytsone lib warning that is within many of our services.
> 2025-02-11 00:49:34.772 9 WARNING keystonemiddleware.auth_token [-] AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
With this change the error is resolved and no longer part of our system.
=> fix: resolve deprecated keystone options

ansible/playbooks/templates/genestack-multipath.conf
Our current regexp pattern ^sda[0-9]* and ^sdb[0-9]* blacklists sda and sdb which is what we want. Unfortunately, it also blocks /dev/sda[a-x], /dev/sdb[a-x] which is NOT what we want Guarav's Rally testing revealed that with a high number of multipath devices, they naming convention starts to add the additional alphabet letter as it scales up.
The correction: "sd[a-b]$" per
https://www.suse.com/support/kb/doc/?id=000016563
=> FIX: HIGH PRIORITY multipath blacklist

.original-images.json
There was an issue with the project id hash which had unforseen breakage with services like octavia. While the hash length is allowed by the keystone driver, a hard coded value in the octavia service limits project IDs to only 32 characters.
This change pulls in a new image that will resolve this hashing issue so that new projects don't encounter this issue.
=> fix(keystone): update the keystone image to fix project id hashing

bin/backup-mariadb.sh, docs/infrastructure-mariadb-ops.md
This change updates the mariadb operators docs so that it references the script backup-databases.sh. This change makes operator life within the genestack platform easier as there's one documented flow, and a set of tools that can be used to achieve goals.
=> fix: update mariadb operators docs

base-helm-configs/ceilometer/ceilometer-helm-overrides.yaml
Cinder volume notifications emit only payload.volume_type as an id, but the API pollster in Ceilometer gets back a name value from Cinder. Cinder should emit the volume_type_name in its notification payloads but sadly it does not at this time. This change will simply re-route payload volume_type to a new field we will add in gnocchi for volume_type_id, preventing flip-flopping of volume_type on the gnocchi volume_type resources.
LPBug: https://bugs.launchpad.net/cinder/+bug/2097328
Change-Id: I71e7fca4a6d303462fa6d0ed69245b79cb28d646
=> fix(ceilometer): Add volume_type_id to metric meta

base-kustomize/gateway/nginx-gateway-fabric/internal-gateway-api.yaml, base-kustomize/gateway/nginx-gateway-fabric/internal-gateway-issuer.yaml, docs/gateway-api-ca-issuer.md, docs/infrastructure-gateway-api.md, mkdocs.yml
I am raising this PR for jira [1]; currently when letsencrypt is not used in a LAB setup selfSigned issuer is being used to issue certificates to gateway-api listeners; this issues a CA certificate to each listener; this requires all the CA certificates for each endpoint to be injected into the client
[1] https://rackspace.atlassian.net/browse/OSPC-1004
=> use selfSigned issuer to bootstrap CA issuer and use that to issue certificates to gateway-api listeners

base-kustomize/barbican/base/barbican-mariadb-database.yaml, base-kustomize/barbican/base/barbican-rabbitmq-queue.yaml, base-kustomize/ceilometer/base/ceilometer-rabbitmq-queue.yaml, base-kustomize/cinder/base/cinder-mariadb-database.yaml, base-kustomize/cinder/base/cinder-rabbitmq-queue.yaml, base-kustomize/designate/base/designate-mariadb-database.yaml, base-kustomize/designate/base/designate-rabbitmq-queue.yaml, base-kustomize/glance/base/glance-mariadb-database.yaml, base-kustomize/glance/base/glance-rabbitmq-queue.yaml, base-kustomize/grafana/base/grafana-database.yaml, base-kustomize/heat/base/heat-mariadb-database.yaml, base-kustomize/horizon/base/horizon-mariadb-database.yaml, base-kustomize/keystone/base/keystone-mariadb-database.yaml, base-kustomize/keystone/base/keystone-rabbitmq-queue.yaml, base-kustomize/magnum/base/magnum-mariadb-database.yaml, base-kustomize/magnum/base/magnum-rabbitmq-queue.yaml, base-kustomize/neutron/base/neutron-mariadb-database.yaml, base-kustomize/neutron/base/neutron-rabbitmq-queue.yaml, base-kustomize/nova/base/nova-mariadb-database.yaml, base-kustomize/nova/base/nova-rabbitmq-queue.yaml, base-kustomize/octavia/base/octavia-mariadb-database.yaml, base-kustomize/octavia/base/octavia-rabbitmq-queue.yaml, base-kustomize/placement/base/placement-mariadb-database.yaml
Our use of app.kubernetes.io/managed-by: "Helm" was set in an annotation but it needed to be in a label. This fixes the glitch.
=> fix: Update the use of managed-by Helm

.github/workflows/release-neutron-oslodb.yaml
This change will allow us to build the master image of neutron using the fixed sync methods. An upstream review has been created to track these changes and ensure that the fixes we're developing are shared with the community.
Upstream: https://review.opendev.org/c/openstack/neutron/+/941824
=> chore: Update image build for neutron

bootstrap.sh
If the bootstrap script is run twice it will fail due to the kustomize symlink already existing. This change updates the bootstrap script so that the symlink create will force the recreation as needed.
=> fix: bootstrap script will fail if ran twice

docs/infrastructure-gateway-api.md
When deploying the gateway api the `/etc/genestack/helm-configs/nginx-gateway-fabric/helm-overrides.yaml` file is not guaranteed to exist, this change updates the docs to ensure that it does.
=> fix: add gateway api overrides reference

ansible/roles/host_setup/files/queue_max.sh
When building cluster with virt nodes, the queue-max service will fail if the interface used is a virtio interface. This change detects the use of virtio and if found the queue max set will skip.
=> fix: add skip for virtio interfaces

Containerfiles/Glance-Containerfile
This change ensures that our glance image so that it resolves errors in the logs with unsupported stores and ensures we're running an up to date, stable version of glance.
=> fix: update the glance store service

base-kustomize/skyline/base/hpa-skyline-apiserver.yaml
The HPA deployment name was wrong, which was leading to hpa not managing the deployment.
=> fix(skyline): Correct HPA deployment name

mkdocs.yml
Within the ops docs we were using openstack project names for sections instead of their purpose. This change updates the ops docs so that they style matches.
=> chore: rename OPS sections

base-helm-configs/ceilometer/ceilometer-helm-overrides.yaml
When one is viewing snapshot resources in gnocchi it is useful to know the volume_id.
=> feat: Add volume_id for snapshots

base-kustomize/octavia/base/hpa-octavia-api.yaml
current memory value is too low forcing max pods to be created
=> chore: Tuning Octavia API HPA

base-helm-configs/glance/glance-helm-overrides.yaml, bin/install-glance.sh, releasenotes/notes/glance-chart-d355eaa64eb4b89c.yaml
This change removes the need to carry the openstack-helm charts for the purposes of providing a glance deployment. The base helm files have been updated and simplified, reducing the values we carry to only what we need.
Related Issue: https://github.com/rackerlabs/genestack/issues/809
=> chore(glance): convert helm chart from submodule to repo

base-helm-configs/keystone/keystone-helm-overrides.yaml, bin/install-keystone.sh, releasenotes/notes/keystone-chart-90138b428d5871b7.yaml
This change removes the need to carry the openstack-helm charts for the purposes of providing a keystone deployment. The base helm files have been updated and simplified, reducing the values we carry to only what we need.
=> chore(keystone): convert helm chart from submodule to repo

base-helm-configs/octavia/octavia-helm-overrides.yaml, base-kustomize/octavia/base/kustomization.yaml, bin/install-octavia.sh, docs/octavia-flavor-and-flavorprofile-guide.md, releasenotes/notes/octavia-chart-4471a89ed3631d45.yaml
This change removes the need to carry the openstack-helm charts for the purposes of providing a octavia deployment. The base helm files have been updated and simplified, reducing the values we carry to only what we need.
=> chore(octavia): convert helm chart from submodule to repo

base-helm-configs/horizon/horizon-helm-overrides.yaml, bin/install-horizon.sh, releasenotes/notes/horizon-chart-dab65a869cc84de3.yaml
This change removes the need to carry the openstack-helm charts for the purposes of providing a horizon deployment. The base helm files have been updated and simplified, reducing the values we carry to only what we need.
=> chore(horizon): convert helm chart from submodule to repo

base-helm-configs/cinder/cinder-helm-overrides.yaml, bin/install-cinder.sh, releasenotes/notes/cinder-chart-3e9c76938ef9ebe8.yaml
This change removes the need to carry the openstack-helm charts for the purposes of providing a cinder deployment. The base helm files have been updated and simplified, reducing the values we carry to only what we need.
=> chore(cinder): convert helm chart from submodule to repo

base-helm-configs/magnum/magnum-helm-overrides.yaml, bin/install-magnum.sh, releasenotes/notes/magnum-chart-5bcf6c0c706a9ad5.yaml
This change removes the need to carry the openstack-helm charts for the purposes of providing a magnum deployment. The base helm files have been updated and simplified, reducing the values we carry to only what we need.
=> chore(magnum): convert helm chart from submodule to repo

base-helm-configs/nova/nova-helm-overrides.yaml, bin/install-nova.sh, releasenotes/notes/nova-chart-f3c262b4d46c5178.yaml
This change removes the need to carry the openstack-helm charts for the purposes of providing a nova deployment. The base helm files have been updated and simplified, reducing the values we carry to only what we need.
=> chore(nova): convert helm chart from submodule to repo

base-helm-configs/placement/placement-helm-overrides.yaml, bin/install-placement.sh, releasenotes/notes/placement-chart-2b02ca15631a0af1.yaml
This change removes the need to carry the openstack-helm charts for the purposes of providing a placement deployment. The base helm files have been updated and simplified, reducing the values we carry to only what we need.
=> chore(placement): convert helm chart from submodule to repo

base-helm-configs/heat/heat-helm-overrides.yaml, bin/install-heat.sh, releasenotes/notes/heat-chart-e469c7543a21ad8e.yaml
This change removes the need to carry the openstack-helm charts for the purposes of providing a heat deployment. The base helm files have been updated and simplified, reducing the values we carry to only what we need.
=> chore(heat): convert helm chart from submodule to repo

base-helm-configs/barbican/barbican-helm-overrides.yaml, bin/install-barbican.sh, docs/openstack-barbican.md, releasenotes/notes/barbican-chart-d7ddbde0e3f6cfd6.yaml
This change removes the need to carry the openstack-helm charts for the purposes of providing a barbican deployment. The base helm files have been updated and simplified, reducing the values we carry to only what we need.
=> chore(barbican): convert helm chart from submodule to repo

.github/workflows/mkdocs.yaml
pandoc from apt makes our reno docs look sad, pandoc from upstrream make our docs look pretty. so lets make our docs look pretty.
=> chore: update pandoc version in our job so our converted docs look pretty

base-helm-configs/gnocchi/gnocchi-helm-overrides.yaml, bin/install-gnocchi.sh, releasenotes/notes/gnocchi-chart-822265ae2b8e6d8b.yaml
This change removes the need to carry the openstack-helm-infra chart for the purposes of providing a libvirt deployment. The base helm file has been updated and simplified, reducing the values we carry to only what we need.
=> chore(gnocchi): convert gnocchi helm chart from submodule to repo

base-helm-configs/ceilometer/ceilometer-helm-overrides.yaml, bin/install-ceilometer.sh, releasenotes/notes/ceilometer-chart-a8655e866388369b.yaml
This change removes the need to carry the openstack-helm chart for the purposes of providing a ceilometer deployment.
The base helm file has been updated and simplified, reducing the values we carry to only what we need.
=> chore(ceilometer): convert ceilometer helm chart from submodule to repo

bin/install-nginx-gateway.sh, bin/setup-nginx-gateway.sh, docs/infrastructure-nginx-gateway-api.md
This change makes the nginx-gateway simpler to deploy by creating and documenting scripts that do all the lifting for our users.
=> chore(nginx-gw): update docs to make it simpler to deploy

docs/monitoring-info.md, docs/prometheus-monitoring-overview.md, docs/prometheus-snmp-exporter.md, mkdocs.yml
JIRA:OSPC-624
This documents the Prometheus SNMP Exporter.
Internally, we configure it for our F5s, but external users would need to plan to configure it on a site and installation specific basis. As it does not monitor anything within Genestack itself, it doesn't have much in the way of default configuration, so I mostly mentioned it exists, how to install it, and that it needs configuration if anyone plans to use it.
=> doc: Prometheus SNMP exporter documentation

base-kustomize/envoyproxy-gateway/base/envoy-custom-proxy-config.yaml, manifests/metallb/metallb-openstack-service-lb.yml
This change will ensure that the envoy deployment for the flex gateway is using an affinity rule that matches the
> node-role.kubernetes.io/worker=worker
This value will ensure that gateways are deployed on our k8s workers.
=> chore: add envoy affinity rules

base-kustomize/envoyproxy-gateway/base/envoy-endpoint-policies.yaml
this change simplified the BackendTrafficPolicy so that all endpoints are using the same least connections policy.
While we can enhance our system with additional policies, we should start simple.
=> Envoy lb policy

ansible/roles/host_setup/defaults/main.yml
Increasing net.netfilter.nf_conntrack_max to 1 million along with adding host_nf_conntrack_buckets
=> Increase net.netfilter.nf_conntrack_max

ansible/playbooks/extra/custom_exporters/perccli.py
Added to additional keys:
- manufacturer
- type (JBOD or "-") This tells us whether the drive is being tracked by the RAID card as part of an array or strictly in pass through mode which is designated for JBOD.
Both of these fields will assist in filters with Prometheus alert rules.
=> Feat: Adding fields to megaraid_pd_info Prometheus exporter data

.pre-commit-config.yaml
Add yamllint to pre-commit to ensure that we are enforcing code standards to our yaml files.
=> feat: add yamllint to pre-commit

ansible/playbooks/extra/custom_exporters/multipathd_info
Simple sed replacement and variable store fixes the prometheus scraped output fields. Tested and confirmed on real data.
=> Fix: multipathd_info field fix for NETAPP,LUN type paths

.pre-commit-config.yaml
configure pre_commit yamllint args to ignore line-length and the submodules directory as everything in submodules is owned by others and we dont care about line-length.
=> chore: ignore line-length and submodules in yamllint

ansible/roles/host_setup/defaults/main.yml
Common CVE scanner mark systems having ICMP redirect enabled, the default configuration is now to disable ICMP redirect on host level
=> Disable ICMP Redirect as common CVE findings

bin/setup-openstack-rc.sh, bin/setup-openstack.sh, scripts/hyperconverged-lab.sh
This change updates the lab and install scripts to use the hyperconverged lab process. The setup scripts will now run in parallel where it can.
A new script was created to generate the openstack rc "clouds" file.
=> feat: add / update scripts for install

base-kustomize/ovn-backup/base/ovn-backup.yaml
looks similar to a previous commit, but the actual version update got lost as I compared checksums of the serialized YAML to make sure the yamllint required changes didn't alter the structure, so I called this one a 'fix' instead of a 'chore'
=> fix: update OVN backup version

scripts/hyperconverged-lab.sh
Check to see if user plans to use SJC3 and if so, offer them a valid flavor for SJC3 (at least, until we get gp.5.8.16 HW there)
Also signed this time
=> fix: detect region and offer a valid flavor in hyperconverged-lab.sh

scripts/hyperconverged-lab.sh
I needed to add SSH agent forwarding to get this working
I'm guessing people it works for have it already picked up by their SSH config
I didn't need it until it tried to run Ansible, but I just edited it so the SSH commands all look the same, even when SSHing wouldn't need it
=> fix: add SSH agent forwarding in hyperconverged-lab.sh

docs/build-test-envs.md, scripts/hyperconverged-lab-uninstall.sh, scripts/hyperconverged-lab.sh
add new environment variable `LAB_NAME_PREFIX` which will allow multiple labs to be built in a single project.
=> chore: add environment variable for lab prefix

.github/workflows/pre-commit.yaml
tj-actions is no longer recommended
CVE-2025-30066
=> fix: Use git to derive changed files instead

ansible/roles/octavia_preconf/files/create_health_mgr_ports.sh
This change ensures that the controller ip addresses are iterated on when discovered. the the "fixed_ips" field from ports is a list, we should expect it to potentially have multiple values.
This change also ensures that our comma separated list of ip addresses is properly formated without a leading space.
The loop will now guard when creating the port so that the script is idempotent.
=> fix: add iterator for IPS

base-kustomize/ovn/ovn-setup.yaml
update the kubernetes-entrypoint image tag from v1.0.0 to latest-ubuntu_jammy for the ovn-setup daemonset otherwise with latest versions the pods are failing to pull the image
=> update kubernetes-entrypoint image tag to latest-ubuntu_jammy 

scripts/hyperconverged-lab.sh
The check would always avoid creating a correct file because there's always one there so the correct metallb vip was not being set
=> fix: Remove check for metallb-openstack-service-lb.yml because one always exists

base-helm-configs/barbican/barbican-helm-overrides.yaml, base-helm-configs/ceilometer/ceilometer-helm-overrides.yaml, base-helm-configs/cinder/cinder-helm-overrides.yaml, base-helm-configs/designate/designate-helm-overrides.yaml, base-helm-configs/glance/glance-helm-overrides.yaml, base-helm-configs/heat/heat-helm-overrides.yaml, base-helm-configs/keystone/keystone-helm-overrides.yaml, base-helm-configs/magnum/magnum-helm-overrides.yaml, base-helm-configs/neutron/neutron-helm-overrides.yaml, base-helm-configs/nova/nova-helm-overrides.yaml, base-helm-configs/octavia/octavia-helm-overrides.yaml, base-helm-configs/placement/placement-helm-overrides.yaml
All db sections for openstack services now use the same default values. Notable changes are to the `connection_recycle_time` which is set to 600, a production ready value taken from Upstream OpenStack-Ansible.
=> chore(oslo-db): update db sections to all be the same

docs/etcd-backup.md
Remove even the impression of passwords from docs.  Instead use the standard \<enter password here\> style.
=> chore: (etcd-backup) generalize secrets

bin/install-barbican.sh, bin/install-ceilometer.sh, bin/install-cinder.sh, bin/install-glance.sh, bin/install-gnocchi.sh, bin/install-heat.sh, bin/install-horizon.sh, bin/install-keystone.sh, bin/install-kube-ovn.sh, bin/install-magnum.sh, bin/install-neutron.sh, bin/install-nova.sh, bin/install-octavia.sh, bin/install-placement.sh, bin/install-sealed-secrets.sh, bin/install-topolvm.sh
Fix the install scripts to properly allow for additional flags such as --debug.
=> fix: (install-scripts) correctly allow for additional flags

base-kustomize/glance/base/kustomization.yaml, base-kustomize/glance/base/patch-glance-bin.yaml
Running glance-api as uwsgi process does not work. In the current setup, snapshots consistently fails with IOError on data read. Running it as non uwsgi process fixes this issue. Until we have more work done on uwsgi process to make it more stable we switch back to running it under normal eventlet python process.
=> Fix(glance-api): Run glance as non uwsgi process

base-helm-configs/glance/glance-helm-overrides.yaml
Now that our glance service is running without uWSGI, we need to up the default workers so that it matches our default expectations.
=> chore: up the native workers for glance

base-helm-configs/barbican/barbican-helm-overrides.yaml, base-helm-configs/ceilometer/ceilometer-helm-overrides.yaml, base-helm-configs/cinder/cinder-helm-overrides.yaml, base-helm-configs/designate/designate-helm-overrides.yaml, base-helm-configs/glance/glance-helm-overrides.yaml, base-helm-configs/heat/heat-helm-overrides.yaml, base-helm-configs/keystone/keystone-helm-overrides.yaml, base-helm-configs/magnum/magnum-helm-overrides.yaml, base-helm-configs/neutron/neutron-helm-overrides.yaml, base-helm-configs/octavia/octavia-helm-overrides.yaml, base-helm-configs/placement/placement-helm-overrides.yaml
In base-helm-configs, we are setting an empty string for the value of mysql_sql_mode.  This is incorrect as helm will try to pass an empty string literal ‘' to the service .conf file.  When the service attempts to make a database connection, it is passing mysql_sql_mode=’'.  when oslo.db is expecting a value to not be set.  
mysql_sql_mode[¶](https://docs.openstack.org/nova/2023.1/configuration/config.html#database.mysql_sql_mode)
The SQL mode to be used for MySQL sessions. This option, including the default, overrides any server-set SQL mode. To use whatever SQL mode is set by the server configuration, set this to no value. Example: mysql_sql_mode=
=> fix: correctly non-set value to pick up openstack default

base-kustomize/kube-ovn/base/kube-ovn-nodeSelector-patch.yaml, base-kustomize/kube-ovn/base/kustomization.yaml, bin/install-kube-ovn.sh
This will ensure that our deployment of kube-ovn-controller is scoped to only
nodes that are labled with the following labels:
* "kube-ovn/role": "master"
* "kubernetes.io/os": "linux"
=> feat: add kustomize to kube-ovn

base-helm-configs/grafana/grafana-helm-overrides.yaml, base-helm-configs/prometheus/prometheus-helm-overrides.yaml
If not strorageClassName is sepcified the default storage class is used. There might be environments where the `general` class name is not used. In genestack we are now defaulting to longhorn-general as the default. Where we need specific class it should be an override, where we dont leave it to use the default.
=> Remove storageclassname from helm config

base-helm-configs/glance/glance-helm-overrides.yaml, docs/openstack-glance.md
Converting Flex policy to default Genestack Glance policy
flex-host-baseline: 85113f87560d1be9eb36e8117d66b5476710f2b2
feat(glance): image_download policy set to prevent export of Rackspace supplied images (#102)
And allow tenants (within project) and glance admins to download the image.
https://rackspace.atlassian.net/browse/OSPC-1210
=> Feat! (Glance): Add sane default policy for image download restrictions

docs/prometheus-blackbox-exporter.md
before running install-chart.sh shell script; genestack.rc script is required to be sourced otherwise the script will fail with permission-denied errors
=> modify prometheus blackbox exporter doc to source genestack.rc

base-helm-configs/prometheus/prometheus-helm-overrides.yaml
The pruned overrides were installing grafana and not allowing monitoring to be discovered. Revert that until we shake it down throughly.
=> fix: Reverting prometheus override pruning to resolve issues

docs/openstack-keystone-federation.md
The default example mapping includes the "creator" role, but it does not exist by default after completing most of the OpenStack setup. To avoid errors when logging in with a valid Rackspace username/password, manually create the "creator" role. Without it, Keystone will return the following error:
> ERROR keystone.auth.plugins.mapped [None-4e390453-680f-4a5d-a315-2a0ac7693033 - - - - - -] Role creator was specified in the mapping but does not exist. All roles specified in a mapping must exist before assignment.
=> docs: Add tip about creating the creator role

base-kustomize/heat/base/kustomization.yaml
The heat liveness probes are failing too fast, especially when the cluster is busy. This change extends the liveness probes so that they're not creating a problem when the cluster is under load.
=> chore: patch the heat liveness probes

bin/create-secrets.sh
modify the "ironic-db-password" and "ironic-rabbitmq-password" variables to "ironic_db_password" and "ironic_rabbitmq_password" otherwise the create-secrets.sh script fails and no passwords for ironic are created
=> modify characters '-' to '_' in ironic db and rabbitmq passwords

requirements.txt
Keystome mapping requires a more current python-openstackclient.  This pr ups the python-openstackclient version to 7.4.0
=> chore: (python-openstackclient) update minimium version

.original-images.json, etc/keystone/mapping.json
This change implements a new keystone image that has deep support for role based access as defined by global auth.
=> feat: add new image for keystone that supports rbac

docs/build-test-envs.md, scripts/hyperconverged-lab.sh
Add endpoints.yaml override to hyperconverged-lab.sh so that external CLI access can be used when lab is created as long as DNS is set correctly.  Also added DNS and access instructions to docs.
=> feat: Enable hyperconverged lab to have external OpenStack CLI access

base-helm-configs/memcached/memcached-helm-overrides.yaml, releasenotes/notes/memcached-placement-be7d472ba25cb94f.yaml
The memcached helm chart now places memcached on the openstack controlplane using the label `openstack-control-plane=enabled`. The min replica set to 1 as default setting.
=> Limit memcached to control plane placement

base-kustomize/rabbitmq-cluster/base/rabbitmq-cluster.yaml, manifests/metallb/metallb-openstack-service-lb.yml, releasenotes/notes/metallb-consolidation-52e5d0d301cc216b.yaml
The metallb configuration is now consolidated and cleaned up by providing the metallb IP address pools:
- `gateway-api-external` for Envoy/Nginx
- `primary` for all internal services including MariaDB, RabbitMQ and others
- The pool `pool1` is replaced by `primary`
=> Consolidate metallb configuration

ansible/playbooks/deploy-cinder-netapp-volumes-reference.yaml, ansible/playbooks/deploy-cinder-volumes-reference.yaml
This update protects against the default ISO install initiator name being used. It also protects against any cloud image type installs that set GenerateName=yes prior to a restart of iscsid service. It predictably sets a unique initiator name. IF the initator name is already set correctly, no action is taken.
=> Feat: Add predictable iscsi initiator name to Ansible playbooks

base-kustomize/keystone/federation/kustomization.yaml
keystone in federation mode runs a shib pod in the keystone-api container.  This pr applies HPA limits and requests to the additional pod so HPA can work.
=> feat: (hpa) add limits to keystone-shib container

base-kustomize/keystone/federation/kustomization.yaml
(cherry picked from commit 4c1667b6a5039b4af829ab970a5854d93b490f1a)
=> feat: (hpa) add limits to keystone-shib container (#1031)

base-kustomize/skyline/base/configmap-bin.yaml
Added the new configuration parameter for the OSPC-696(Create a new Skyline option that allows an administrator to set the "default" domain).
-->Default value of the config parameter for 'default_domain' is 'Default' in cofigmap-bin.yaml - It allows the system to adapt to existing behaviour, which is 'Default' domain.
-->If admin wants to change the 'default_domain' parameter value to  to some other value during deployment, 
For example : default_domain: 'rackspace_cloud_domain' has set inside the configmap-bin.yaml.
Then the default domain will be changed to 'rackspace_cloud_domain'  from 'Default' value.
--> So the default value of config parameter 'default_domain' will be always set to 'Default' value, untill and unless we are
changing it.
=> OSPC-696:Added new default_domain config parameter for OSPC-696

.original-images.json, base-kustomize/skyline/base/configmap-bin.yaml, etc/keystone/mapping.json
Pull in the keystone mapping file for federated auth along with a skyline bug fix for cinder services.
=> Release 2.3.1

ansible/playbooks/deploy-cinder-netapp-volumes-reference.yaml, ansible/playbooks/deploy-cinder-volumes-reference.yaml, ansible/playbooks/host-setup.yml, docs/openstack-cinder-lvmisci.md, scripts/hyperconverged-lab.sh
This PR updates documentation and playbooks to implement the inventory variable 'storage_network_multipath' updated in the flex-host-baseline PR:
https://github.com/rackerlabs/flex-host-baseline/pull/160. This variable more closely describes dual network storage interfaces being set up on the storage nodes rather than the overloaded inventory variable 'custom_multipath' which is used in host-setup.yml to primarily copy the multipath.conf.j2 template file for compute nodes.
=> fix(cinder): differentiate multipath networking and conf file

docs/openstack-cloud-design-ha.md
Fix mermaid diagrams to be more clear about instance migrations across HAs vs AZs
=> fix: Update HA diagrams for clarity

base-helm-configs/kube-ovn/kube-ovn-helm-overrides.yaml
Updating our defaults to use the new tuned options we're running in production.
=> chore: tune kube-ovn

ansible/playbooks/extra/custom_exporters/md_info_detail.sh
Removes trailing whitespace in state and Status fields. Previously, alerts may have been triggered or not have been triggered because the pattern in the Prometheus rule might have taken the whitespace into account. This removes that possibility until this bash script can be re-written in Python instrumentation for Prometheus.
=> Fix: md_info_detail.sh

base-helm-configs/ceilometer/ceilometer-helm-overrides.yaml
Correct an error where we were defining empty dicts for overrides to openstack-helm ceilometer chart on hpa requests/limits.  only override what we actually want to change and use the helm chart for all other defaults.
=> fix: only define values we are overriding

base-helm-configs/nova/nova-helm-overrides.yaml
Aligns override structure with the base chart by moving lifecycle settings to the `pod` section. This fixes an issue where overrides were not being applied.
=> fix(nova): Correct path for lifecycle overrides

base-helm-configs/nova/nova-helm-overrides.yaml
Octavia when it creates an instance is forcing config_drive to be true.  When using static vendordata, the payload needs to live in the nova-compute pods when config_drive is true.  Enable the mount point into the nova-compute pods.
=> fix: add static vendordata mount point to nova-compute pods

base-helm-configs/neutron/neutron-helm-overrides.yaml
This change adds limits to our metadata servers which will be essential to ensuring we maintain a stable environment.
Docs: https://docs.openstack.org/neutron/2024.1/admin/config-metadata-rate-limiting.html
=> feat: add metadata ratelimits

base-kustomize/skyline/base/deployment-apiserver.yaml
The basic skyline limits were set so low that the HPA would scale to the max for no reason. This change sets the skyline limits to a more sane value for a typical small scale environment.
=> fix: unify the skyline limits

base-helm-configs/neutron/neutron-helm-overrides.yaml
Increasing max_pool_size from 5 (default value) to 30, and max_overflow from 50 to 60.
=> fix: OSPC-1358: Neutron server QueuePool limit exceeded

base-helm-configs/redis-operator/redis-operator-helm-overrides.yaml, bin/install-redis-operator.sh, docs/redis-setup-guide.md
->Have got the the redis-operator from the Miguel Parada as https://github.com/OT-CONTAINER-KIT/redis-operator, which is used for a customer POC, and it went with that one because it seems to be the best bet for long term community support, they have deployed it on a platform9 cluster, and the customer deployed redis with it and they have not see any issues or failover scenarios.
->So , hence considered to use this redis operaor further, after discussed with Phillip.
->Customer using the standalone deployment, but I have used the cluster deployment, have used the redis-cluster for redis instance deployment.
->I have tested in my local cluster with these details, and shared the result in the attached file.
[Redis_Test_Result_On_Local_Cluster.zip](https://github.com/user-attachments/files/21 …
=> OSPC-1403: added the script , values.yaml and docs for redis operator

ansible/playbooks/deploy-cinder-netapp-volumes-reference.yaml, ansible/playbooks/templates/eventlet_ssl_patch.py, ansible/playbooks/templates/zzz_eventlet_ssl_patch.pth
This ensures that username/pass are not sent in clear text. This does NOT encrypt all traffic from virtual machines to attached NetApp volumes.
Adds variables and logic to playbook for SSL cert deployment to storage node. Correctly updates ca certificates on storage node based on Linux OS version. This assumes DNS resolution for the NetApp cluster hostname and NetApp vserver name.
=> Feat: Add SSL encryption between cinder-volume Ontap driver and NetApp

scripts/hyperconverged-lab.sh
This pr moves hyperconverged.sh back to cloning from genetsack.
=> fix: move back to cloning from genestack

ansible/roles/host_setup/handlers/main.yml, ansible/roles/host_setup/tasks/main.yml, ansible/roles/host_setup/vars/debian.yml, ansible/roles/host_setup/vars/ubuntu.yml
The following configuration will ensure that we're not permitting LLDP traffic over tenant networks. In the before now we were not controlling the installation of LLDP, however, we were requiring it for QC tools. This change ensures that we're controlling the installation of LLDP and the config, which ensures that we're not leaking host information to tenants of the cloud platform.
=> fix: ensure no-tenant network leakage

scripts/hyperconverged-lab.sh
fix: ensure newline at end of script and standardize EOC
The POSIX standard for text files requires a final newline character. Many utilities, including compilers, linters, and text editors, can behave unexpectedly if this rule isn't followed. Adding the newline ensures that your script is properly terminated and that all of its content, including the delimiter, is correctly parsed. This consistency makes your script more portable and less prone to errors when processed by different tools or on different systems.
=> fix: standardize EOC in script

base-helm-configs/masakari/masakari-helm-overrides.yaml
Related to PR https://github.com/rackerlabs/genestack-images/pull/71
Fix broken image pull for masakari-monitors process and instance monitor when migrating from quay.io to ghcr.io registry.
=> adjust masakari-monitors genestack image repo link

ansible/playbooks/deploy-cinder-netapp-volumes-reference.yaml, ansible/roles/host_setup/tasks/raid_cli_tools.yml
Added remote_src to host-setup so that gunzip/unarchive works properly.
deploy-cinder-netapp-volumes-reference now addresses different versions of python rather than hardcoding for site-packages path. Tested in SJC after deploy to prove remediation of the problems.
=> Fix: Ansible host-setup and deploy-cinder-netapp-volumes-reference

docs/openstack-exporter.md
Corrected the secret name in the openstack-exporter.md file from "keystone-auth" to correct name as "keystone-auth-openstack-exporter".
=> OSPC-1364:Corrected the secret name in .md file

base-helm-configs/prometheus/prometheus-helm-overrides.yaml
(cherry picked from commit 39356c740272ead513f3c4963e0c1af727f9a520)
=> fix: correct list override for exemplars

base-helm-configs/freezer/freezer-helm-overrides.yaml, bin/create-secrets.sh, bin/install-freezer.sh
1. Making Freezer-Client VM to communicate explicitly over public endpoint using the service tenant - hence enabling the service-password for the freezer public endpoint.
2. On non-public endpoints, in my testing its seen freezer requires the backup api version to be set on endpoint urls.
=> fix: Add freezer-keystone-service-password and v2 on non-public endpoints

base-helm-configs/placement/placement-helm-overrides.yaml
The `oslo_concurrency.lock_path` in `placement-helm-overrides.yaml` was incorrectly set to `/tmp/octavia`. This appears to be a copy-paste error from the Octavia service configuration.
(cherry picked from commit 0c1f2a75ef549251cf414f2894124d2a0c75e779)
=> fix(placement): Correct incorrect oslo_concurrency lock_path (#1220)

base-helm-configs/freezer/freezer-helm-overrides.yaml
Already v2 is present in python-freezerclient code: 
[https://opendev.org/openstack/python-freezerclient/src/branch/master/freezerclient/v2/managers/sessions.py#L27](https://opendev.org/openstack/python-freezerclient/src/branch/master/freezerclient/v2/managers/sessions.py#L27) 
This was creating an incorrect url causing API calls to fail.
=> fix: Remove v2 on non-public endpoints
